/**************************************************************************** 
* 
* Copyright (c) 2023  C*Core -   All Rights Reserved  
* 
* THIS SOFTWARE IS DISTRIBUTED "AS IS," AND ALL WARRANTIES ARE DISCLAIMED, 
* INCLUDING MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* 
*   Project              : AUTOSAR 4.4.0 MCAL
*   Platform             : PowerPC e200
*   Peripheral           : 
*   Dependencies         : 
*
*   Autosar Version      : 4.4.0
*   Autosar Revision     : 
*   Autosar Conf.Variant :
*   SW Version           : 
*   Build Version        : 
*  
*****************************************************************************/

/**
*   @file    eDma_Cfg.c
*   @version 
*
*   @brief   AUTOSAR 4.4.0 - Common Level Driver source file.
*   @details Autosar layer of eDma MCAL driver.
*
*   @addtogroup eDma
*   @{
*/

#ifdef __cplusplus
extern "C"{
#endif

#include "eDma.h"

#define EDMA_CFG_C_VENDOR_ID                     176
#define EDMA_CFG_C_AR_REL_MAJOR_VER              4
#define EDMA_CFG_C_AR_REL_MINOR_VER              4
#define EDMA_CFG_C_AR_REL_REV_VER                0
#define EDMA_CFG_C_SW_MAJOR_VER                  1
#define EDMA_CFG_C_SW_MINOR_VER                  0
#define EDMA_CFG_C_SW_PATCH_VER                  1

#if (MCAL_VENDOR_ID != EDMA_CFG_C_VENDOR_ID)
    #error " NON-MATCHED DATA : EDMA_CFG_C_VENDOR_ID "
#endif
#if (MCAL_AR_RELEASE_MAJOR_VERSION != EDMA_CFG_C_AR_REL_MAJOR_VER)
    #error " NON-MATCHED DATA : EDMA_CFG_C_AR_REL_MAJOR_VER "
#endif
#if (MCAL_AR_RELEASE_MINOR_VERSION != EDMA_CFG_C_AR_REL_MINOR_VER)
    #error " NON-MATCHED DATA : EDMA_CFG_C_AR_REL_MINOR_VER "
#endif
#if (MCAL_AR_RELEASE_REVISION_VERSION != EDMA_CFG_C_AR_REL_REV_VER)
    #error " NON-MATCHED DATA : EDMA_CFG_C_AR_REL_REV_VER "
#endif
#if (MCAL_SW_MAJOR_VERSION != EDMA_CFG_C_SW_MAJOR_VER)
    #error " NON-MATCHED DATA : EDMA_CFG_C_SW_MAJOR_VER "
#endif
#if (MCAL_SW_MINOR_VERSION != EDMA_CFG_C_SW_MINOR_VER)
    #error " NON-MATCHED DATA : EDMA_CFG_C_SW_MINOR_VER "
#endif
#if (MCAL_SW_PATCH_VERSION != EDMA_CFG_C_SW_PATCH_VER)
    #error " NON-MATCHED DATA : EDMA_CFG_C_SW_PATCH_VER "
#endif

[!SELECT "eDmaConfigSet"!]
    [!INDENT "0"!]
        [!LOOP "eDmaChannelConfig/*"!]
            [!IF "(normalize-space(eDmaChCallbaceFunction) != 'NULL_PTR')"!]
                extern void [!"normalize-space(eDmaChCallbaceFunction)"!](const void *parameter, eDMAChnStatusType status, uint8 mappedChannel);
            [!ENDIF!]
        [!ENDLOOP!]
    [!ENDINDENT!]
[!ENDSELECT!]

[!AUTOSPACING!]
[!NOCODE!]
[!SELECT "eDmaConfigSet"!]
    [!LOOP "eDmaChannelConfig/*"!]
        [!VAR "ChannelID" = "./eDmaChannelId"!]
        [!VAR "ChannelName" = "@name"!]
        [!VAR "ChannelSource" = "./eDmaChannelReqSource"!]
        [!VAR "ChannelIndex" = "@index"!]
        [!LOOP "../../eDmaChannelConfig/*"!]
            [!IF "$ChannelIndex != @index"!]
                [!IF "$ChannelID = ./eDmaChannelId"!]
                    [!ERROR!][[!"$ChannelName"!]] and [[!"@name"!]] The same chanel is configured, please change to a different chanel configuration[!ENDERROR!]
                [!ENDIF!]
                [!IF "$ChannelSource = ./eDmaChannelReqSource"!]
                    [!ERROR!][[!"$ChannelName"!]] and [[!"@name"!]] are configured with the same source. Please change the source[!ENDERROR!]
                [!ENDIF!]
            [!ENDIF!]
        [!ENDLOOP!]
    [!ENDLOOP!]
[!ENDSELECT!]
[!ENDNOCODE!]

[!NOCODE!]
[!SELECT "eDmaConfigSet"!]
    [!LOOP "eDmaChannelConfig/*"!]
        [!VAR "eDmaInstance_temp" = "./eDmaInstance"!]
        [!VAR "eDmaGroupId_temp" = "./eDmaGroupId"!]
        [!VAR "eDmaChannelPriority_temp" = "./eDmaChannelPriority"!]
        [!VAR "ChannelName" = "@name"!]
        [!VAR "ChannelIndex" = "@index"!]
        [!LOOP "../../eDmaChannelConfig/*"!]
            [!IF "$ChannelIndex != @index"!]
                [!IF "num:i(eDmaInstance) = num:i($eDmaInstance_temp) and num:i(eDmaGroupId) = num:i($eDmaGroupId_temp) and eDmaChannelPriority = $eDmaChannelPriority_temp"!]
                    [!ERROR!][[!"$ChannelName"!]] and [[!"@name"!]] are configured with the same eDmaChannelPriority. Please change the eDmaChannelPriority[!ENDERROR!]
                [!ENDIF!]
            [!ENDIF!]
        [!ENDLOOP!]
    [!ENDLOOP!]
[!ENDSELECT!]
[!ENDNOCODE!]

[!SELECT "eDmaConfigSet"!]
    [!INDENT "0"!]
        [!LOOP "eDmaChannelConfig/*"!]
            VAR(eDMAChanConfigType, AUTOMATIC) [!"@name"!]_Config =
            {
                [!INDENT "4"!]
                .chnPrioSet = [!"eDmaChannelPriority"!],
                .mappedChnConfig = [!"eDmaChannelId"!],
                .reqSource = [!"eDmaChannelReqSource"!],
                [!IF "(normalize-space(eDmaChCallbaceFunction) != 'NULL_PTR')"!]
                    .callback = &[!"normalize-space(eDmaChCallbaceFunction)"!],
                [!ELSE!]
                    .callback = NULL_PTR,
                [!ENDIF!]
                [!IF "(normalize-space(eDmaChCallbaceParam) != 'NULL_PTR')"!]
                    .callbackParam = &[!"normalize-space(eDmaChCallbaceParam)"!],
                [!ELSE!]
                    .callbackParam = NULL_PTR,
                [!ENDIF!]
                [!IF "eDmaChTriggerEn = 'true'"!]
                    .triggerEn = TRUE,
                [!ELSE!]
                    .triggerEn = FALSE,
                [!ENDIF!]
                [!IF "eDmaChErrIntEn = 'true'"!]
                    .chnErrIntEn = TRUE,
                [!ELSE!]
                    .chnErrIntEn = FALSE,
                [!ENDIF!]
                [!IF "eDmaPreemptionEn = 'true'"!]
                    .preemptionEn = TRUE,
                [!ELSE!]
                    .preemptionEn = FALSE,
                [!ENDIF!]
                [!IF "eDmaPreemptAbilityDisable = 'true'"!]
                    .preemptAbilityDisable = TRUE,
                [!ELSE!]
                    .preemptAbilityDisable = FALSE,
                [!ENDIF!]
                [!IF "eDmaMasterIdReplicationEn = 'true'"!]
                    .MasterIdReplicationEn = TRUE,
                [!ELSE!]
                    .MasterIdReplicationEn = FALSE,
                [!ENDIF!]
                [!ENDINDENT!]
            };
        [!ENDLOOP!]
    [!ENDINDENT!]
[!ENDSELECT!]


[!SELECT "eDmaConfigSet"!]
    [!INDENT "0"!]
        [!LOOP "eDmaChannelConfig/*"!]
            static VAR(eDMAChnStateType, AUTOMATIC) [!"@name"!]_State;
        [!ENDLOOP!]
    [!ENDINDENT!]
[!ENDSELECT!]

CONST(eDMAModuleConfigType, EDMA_CONST) dmaconfigure_InitConfig[EDMA_INSTANCE_COUNT] = {
    [!SELECT "eDmaConfigSet/eDmaController/*"!]
    [!INDENT "4"!]
    {
        [!INDENT "8"!]
            .setChnArbitMode = [!"ChnArbitMode"!],
            .groupArbitration = [!"groupArbitration"!],
            .prioGroup0 = [!"prioGroup0"!],
            .prioGroup1 = [!"prioGroup1"!],
            .prioGroup2 = [!"prioGroup2"!],
            .prioGroup3 = [!"prioGroup3"!],
            [!IF "haltOnError = 'true'"!]
                .haltOnError = FALSE
            [!ELSE!]
                .haltOnError = FALSE
            [!ENDIF!]
        [!ENDINDENT!]
    },
    [!ENDINDENT!]
    [!ENDSELECT!]
};

CONST(eDMAChPriorityCfg, EDMA_CONST) dmaChPriorityCfgs[EDMA_TOTAL_CHANNELS] = {
    [!VAR "eDmaPriority0_temp" = "num:i(0)"!]
    [!VAR "eDmaPriority1_temp" = "num:i(0)"!]
    [!VAR "eDmaPriority2_temp" = "num:i(0)"!]
    [!VAR "eDmaPriority3_temp" = "num:i(0)"!]
    [!VAR "eDmaPriority4_temp" = "num:i(0)"!]
    [!VAR "eDmaPriority5_temp" = "num:i(0)"!]
    [!VAR "eDmaPriority6_temp" = "num:i(0)"!]
    [!VAR "eDmaPriority7_temp" = "num:i(0)"!]
    [!VAR "eDmaPriority8_temp" = "num:i(0)"!]
    [!VAR "eDmaPriority9_temp" = "num:i(0)"!]
    [!VAR "eDmaPriority10_temp" = "num:i(0)"!]
    [!VAR "eDmaPriority11_temp" = "num:i(0)"!]
    [!VAR "eDmaPriority12_temp" = "num:i(0)"!]
    [!VAR "eDmaPriority13_temp" = "num:i(0)"!]
    [!VAR "eDmaPriority14_temp" = "num:i(0)"!]
    [!VAR "eDmaPriority15_temp" = "num:i(0)"!]
    [!FOR "i" = "0" TO "num:i(128 - 1)"!]
    [!INDENT "4"!]
    {
        [!IF "num:i($i) = num:i(16) or num:i($i) = num:i(32) or num:i($i) = num:i(48) or num:i($i) = num:i(64) or num:i($i) = num:i(80) or num:i($i) = num:i(96) or num:i($i) = num:i(112)"!]
            [!VAR "eDmaPriority0_temp" = "num:i(0)"!]
            [!VAR "eDmaPriority1_temp" = "num:i(0)"!]
            [!VAR "eDmaPriority2_temp" = "num:i(0)"!]
            [!VAR "eDmaPriority3_temp" = "num:i(0)"!]
            [!VAR "eDmaPriority4_temp" = "num:i(0)"!]
            [!VAR "eDmaPriority5_temp" = "num:i(0)"!]
            [!VAR "eDmaPriority6_temp" = "num:i(0)"!]
            [!VAR "eDmaPriority7_temp" = "num:i(0)"!]
            [!VAR "eDmaPriority8_temp" = "num:i(0)"!]
            [!VAR "eDmaPriority9_temp" = "num:i(0)"!]
            [!VAR "eDmaPriority10_temp" = "num:i(0)"!]
            [!VAR "eDmaPriority11_temp" = "num:i(0)"!]
            [!VAR "eDmaPriority12_temp" = "num:i(0)"!]
            [!VAR "eDmaPriority13_temp" = "num:i(0)"!]
            [!VAR "eDmaPriority14_temp" = "num:i(0)"!]
            [!VAR "eDmaPriority15_temp" = "num:i(0)"!]
        [!ENDIF!]
        [!IF "num:i($i) < num:i(16)"!]
            [!SELECT "eDmaConfigSet"!]
                [!LOOP "eDmaChannelConfig/*"!]
                    [!VAR "eDmaChID" = "num:i(substring-before(substring-after(eDmaChannelId,'EDMA_CHN'),'_'))"!]
                    [!IF "$eDmaChID < num:i(16)"!]
                        [!VAR "eDmachPriority_temp" = "eDmaChannelPriority"!]
                        [!IF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY0'"!]
                            [!VAR "eDmaPriority0_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY1'"!]
                            [!VAR "eDmaPriority1_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY2'"!]
                            [!VAR "eDmaPriority2_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY3'"!]
                            [!VAR "eDmaPriority3_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY4'"!]
                            [!VAR "eDmaPriority4_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY5'"!]
                            [!VAR "eDmaPriority5_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY6'"!]
                            [!VAR "eDmaPriority6_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY7'"!]
                            [!VAR "eDmaPriority7_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY8'"!]
                            [!VAR "eDmaPriority8_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY9'"!]
                            [!VAR "eDmaPriority9_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY10'"!]
                            [!VAR "eDmaPriority10_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY11'"!]
                            [!VAR "eDmaPriority11_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY12'"!]
                            [!VAR "eDmaPriority12_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY13'"!]
                            [!VAR "eDmaPriority13_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY14'"!]
                            [!VAR "eDmaPriority14_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY15'"!]
                            [!VAR "eDmaPriority15_temp" = "num:i(1)"!]
                        [!ENDIF!]
                    [!ENDIF!]
                [!ENDLOOP!]
            [!ENDSELECT!]
        [!ELSEIF "num:i($i) < num:i(32)"!]
            [!SELECT "eDmaConfigSet"!]
                [!LOOP "eDmaChannelConfig/*"!]
                    [!VAR "eDmaChID" = "num:i(substring-before(substring-after(eDmaChannelId,'EDMA_CHN'),'_'))"!]
                    [!IF "$eDmaChID < num:i(32) and $eDmaChID > num:i(15)"!]
                        [!VAR "eDmachPriority_temp" = "eDmaChannelPriority"!]
                        [!IF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY0'"!]
                            [!VAR "eDmaPriority0_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY1'"!]
                            [!VAR "eDmaPriority1_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY2'"!]
                            [!VAR "eDmaPriority2_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY3'"!]
                            [!VAR "eDmaPriority3_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY4'"!]
                            [!VAR "eDmaPriority4_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY5'"!]
                            [!VAR "eDmaPriority5_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY6'"!]
                            [!VAR "eDmaPriority6_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY7'"!]
                            [!VAR "eDmaPriority7_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY8'"!]
                            [!VAR "eDmaPriority8_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY9'"!]
                            [!VAR "eDmaPriority9_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY10'"!]
                            [!VAR "eDmaPriority10_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY11'"!]
                            [!VAR "eDmaPriority11_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY12'"!]
                            [!VAR "eDmaPriority12_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY13'"!]
                            [!VAR "eDmaPriority13_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY14'"!]
                            [!VAR "eDmaPriority14_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY15'"!]
                            [!VAR "eDmaPriority15_temp" = "num:i(1)"!]
                        [!ENDIF!]
                    [!ENDIF!]
                [!ENDLOOP!]
            [!ENDSELECT!]
        [!ELSEIF "num:i($i) < num:i(48)"!]
            [!SELECT "eDmaConfigSet"!]
                [!LOOP "eDmaChannelConfig/*"!]
                    [!VAR "eDmaChID" = "num:i(substring-before(substring-after(eDmaChannelId,'EDMA_CHN'),'_'))"!]
                    [!IF "$eDmaChID < num:i(48) and $eDmaChID > num:i(31)"!]
                        [!VAR "eDmachPriority_temp" = "eDmaChannelPriority"!]
                        [!IF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY0'"!]
                            [!VAR "eDmaPriority0_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY1'"!]
                            [!VAR "eDmaPriority1_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY2'"!]
                            [!VAR "eDmaPriority2_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY3'"!]
                            [!VAR "eDmaPriority3_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY4'"!]
                            [!VAR "eDmaPriority4_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY5'"!]
                            [!VAR "eDmaPriority5_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY6'"!]
                            [!VAR "eDmaPriority6_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY7'"!]
                            [!VAR "eDmaPriority7_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY8'"!]
                            [!VAR "eDmaPriority8_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY9'"!]
                            [!VAR "eDmaPriority9_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY10'"!]
                            [!VAR "eDmaPriority10_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY11'"!]
                            [!VAR "eDmaPriority11_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY12'"!]
                            [!VAR "eDmaPriority12_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY13'"!]
                            [!VAR "eDmaPriority13_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY14'"!]
                            [!VAR "eDmaPriority14_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY15'"!]
                            [!VAR "eDmaPriority15_temp" = "num:i(1)"!]
                        [!ENDIF!]
                    [!ENDIF!]
                [!ENDLOOP!]
            [!ENDSELECT!]
        [!ELSEIF "num:i($i) < num:i(64)"!]
            [!SELECT "eDmaConfigSet"!]
                [!LOOP "eDmaChannelConfig/*"!]
                    [!VAR "eDmaChID" = "num:i(substring-before(substring-after(eDmaChannelId,'EDMA_CHN'),'_'))"!]
                    [!IF "$eDmaChID < num:i(64) and $eDmaChID > num:i(47)"!]
                        [!VAR "eDmachPriority_temp" = "eDmaChannelPriority"!]
                        [!IF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY0'"!]
                            [!VAR "eDmaPriority0_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY1'"!]
                            [!VAR "eDmaPriority1_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY2'"!]
                            [!VAR "eDmaPriority2_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY3'"!]
                            [!VAR "eDmaPriority3_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY4'"!]
                            [!VAR "eDmaPriority4_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY5'"!]
                            [!VAR "eDmaPriority5_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY6'"!]
                            [!VAR "eDmaPriority6_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY7'"!]
                            [!VAR "eDmaPriority7_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY8'"!]
                            [!VAR "eDmaPriority8_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY9'"!]
                            [!VAR "eDmaPriority9_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY10'"!]
                            [!VAR "eDmaPriority10_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY11'"!]
                            [!VAR "eDmaPriority11_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY12'"!]
                            [!VAR "eDmaPriority12_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY13'"!]
                            [!VAR "eDmaPriority13_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY14'"!]
                            [!VAR "eDmaPriority14_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY15'"!]
                            [!VAR "eDmaPriority15_temp" = "num:i(1)"!]
                        [!ENDIF!]
                    [!ENDIF!]
                [!ENDLOOP!]
            [!ENDSELECT!]
        [!ELSEIF "num:i($i) < num:i(80)"!]
            [!SELECT "eDmaConfigSet"!]
                [!LOOP "eDmaChannelConfig/*"!]
                    [!VAR "eDmaChID" = "num:i(substring-before(substring-after(eDmaChannelId,'EDMA_CHN'),'_'))"!]
                    [!IF "$eDmaChID < num:i(80) and $eDmaChID > num:i(63)"!]
                        [!VAR "eDmachPriority_temp" = "eDmaChannelPriority"!]
                        [!IF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY0'"!]
                            [!VAR "eDmaPriority0_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY1'"!]
                            [!VAR "eDmaPriority1_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY2'"!]
                            [!VAR "eDmaPriority2_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY3'"!]
                            [!VAR "eDmaPriority3_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY4'"!]
                            [!VAR "eDmaPriority4_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY5'"!]
                            [!VAR "eDmaPriority5_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY6'"!]
                            [!VAR "eDmaPriority6_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY7'"!]
                            [!VAR "eDmaPriority7_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY8'"!]
                            [!VAR "eDmaPriority8_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY9'"!]
                            [!VAR "eDmaPriority9_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY10'"!]
                            [!VAR "eDmaPriority10_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY11'"!]
                            [!VAR "eDmaPriority11_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY12'"!]
                            [!VAR "eDmaPriority12_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY13'"!]
                            [!VAR "eDmaPriority13_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY14'"!]
                            [!VAR "eDmaPriority14_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY15'"!]
                            [!VAR "eDmaPriority15_temp" = "num:i(1)"!]
                        [!ENDIF!]
                    [!ENDIF!]
                [!ENDLOOP!]
            [!ENDSELECT!]
        [!ELSEIF "num:i($i) < num:i(96)"!]
            [!SELECT "eDmaConfigSet"!]
                [!LOOP "eDmaChannelConfig/*"!]
                    [!VAR "eDmaChID" = "num:i(substring-before(substring-after(eDmaChannelId,'EDMA_CHN'),'_'))"!]
                    [!IF "$eDmaChID < num:i(96) and $eDmaChID > num:i(79)"!]
                        [!VAR "eDmachPriority_temp" = "eDmaChannelPriority"!]
                        [!IF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY0'"!]
                            [!VAR "eDmaPriority0_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY1'"!]
                            [!VAR "eDmaPriority1_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY2'"!]
                            [!VAR "eDmaPriority2_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY3'"!]
                            [!VAR "eDmaPriority3_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY4'"!]
                            [!VAR "eDmaPriority4_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY5'"!]
                            [!VAR "eDmaPriority5_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY6'"!]
                            [!VAR "eDmaPriority6_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY7'"!]
                            [!VAR "eDmaPriority7_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY8'"!]
                            [!VAR "eDmaPriority8_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY9'"!]
                            [!VAR "eDmaPriority9_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY10'"!]
                            [!VAR "eDmaPriority10_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY11'"!]
                            [!VAR "eDmaPriority11_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY12'"!]
                            [!VAR "eDmaPriority12_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY13'"!]
                            [!VAR "eDmaPriority13_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY14'"!]
                            [!VAR "eDmaPriority14_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY15'"!]
                            [!VAR "eDmaPriority15_temp" = "num:i(1)"!]
                        [!ENDIF!]
                    [!ENDIF!]
                [!ENDLOOP!]
            [!ENDSELECT!]
        [!ELSEIF "num:i($i) < num:i(112)"!]
            [!SELECT "eDmaConfigSet"!]
                [!LOOP "eDmaChannelConfig/*"!]
                    [!VAR "eDmaChID" = "num:i(substring-before(substring-after(eDmaChannelId,'EDMA_CHN'),'_'))"!]
                    [!IF "$eDmaChID < num:i(112) and $eDmaChID > num:i(95)"!]
                        [!VAR "eDmachPriority_temp" = "eDmaChannelPriority"!]
                        [!IF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY0'"!]
                            [!VAR "eDmaPriority0_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY1'"!]
                            [!VAR "eDmaPriority1_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY2'"!]
                            [!VAR "eDmaPriority2_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY3'"!]
                            [!VAR "eDmaPriority3_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY4'"!]
                            [!VAR "eDmaPriority4_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY5'"!]
                            [!VAR "eDmaPriority5_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY6'"!]
                            [!VAR "eDmaPriority6_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY7'"!]
                            [!VAR "eDmaPriority7_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY8'"!]
                            [!VAR "eDmaPriority8_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY9'"!]
                            [!VAR "eDmaPriority9_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY10'"!]
                            [!VAR "eDmaPriority10_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY11'"!]
                            [!VAR "eDmaPriority11_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY12'"!]
                            [!VAR "eDmaPriority12_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY13'"!]
                            [!VAR "eDmaPriority13_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY14'"!]
                            [!VAR "eDmaPriority14_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY15'"!]
                            [!VAR "eDmaPriority15_temp" = "num:i(1)"!]
                        [!ENDIF!]
                    [!ENDIF!]
                [!ENDLOOP!]
            [!ENDSELECT!]
        [!ELSEIF "num:i($i) < num:i(128)"!]
            [!SELECT "eDmaConfigSet"!]
                [!LOOP "eDmaChannelConfig/*"!]
                    [!VAR "eDmaChID" = "num:i(substring-before(substring-after(eDmaChannelId,'EDMA_CHN'),'_'))"!]
                    [!IF "$eDmaChID < num:i(128) and $eDmaChID > num:i(111)"!]
                        [!VAR "eDmachPriority_temp" = "eDmaChannelPriority"!]
                        [!IF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY0'"!]
                            [!VAR "eDmaPriority0_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY1'"!]
                            [!VAR "eDmaPriority1_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY2'"!]
                            [!VAR "eDmaPriority2_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY3'"!]
                            [!VAR "eDmaPriority3_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY4'"!]
                            [!VAR "eDmaPriority4_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY5'"!]
                            [!VAR "eDmaPriority5_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY6'"!]
                            [!VAR "eDmaPriority6_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY7'"!]
                            [!VAR "eDmaPriority7_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY8'"!]
                            [!VAR "eDmaPriority8_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY9'"!]
                            [!VAR "eDmaPriority9_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY10'"!]
                            [!VAR "eDmaPriority10_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY11'"!]
                            [!VAR "eDmaPriority11_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY12'"!]
                            [!VAR "eDmaPriority12_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY13'"!]
                            [!VAR "eDmaPriority13_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY14'"!]
                            [!VAR "eDmaPriority14_temp" = "num:i(1)"!]
                        [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY15'"!]
                            [!VAR "eDmaPriority15_temp" = "num:i(1)"!]
                        [!ENDIF!]
                    [!ENDIF!]
                [!ENDLOOP!]
            [!ENDSELECT!]
        [!ENDIF!]
        [!INDENT "8"!]
        .channel = [!"concat('EDMA_CHN', $i, '_NUMBER')"!],
        [!VAR "eDmaChIsUsed_temp" = "num:i(0)"!]
        [!VAR "eDmachPriority_temp" = "'EDMA_CHN_PRIORITY_DEFALUT'"!]
        [!VAR "eDmaCh" = "concat('EDMA_CHN', $i, '_NUMBER')"!]
        [!SELECT "eDmaConfigSet"!]
            [!LOOP "eDmaChannelConfig/*"!]
                [!IF "eDmaChannelId = $eDmaCh"!]
                    [!VAR "eDmaChIsUsed_temp" = "num:i(1)"!]
                    [!VAR "eDmachPriority_temp" = "eDmaChannelPriority"!]
                [!ENDIF!]
            [!ENDLOOP!]
        [!ENDSELECT!]
        [!IF "$eDmaChIsUsed_temp = num:i(1)"!]
            .isUsed = TRUE,
            .chPriority = [!"$eDmachPriority_temp"!]
            [!IF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY0'"!]
                [!VAR "eDmaPriority0_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY1'"!]
                [!VAR "eDmaPriority1_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY2'"!]
                [!VAR "eDmaPriority2_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY3'"!]
                [!VAR "eDmaPriority3_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY4'"!]
                [!VAR "eDmaPriority4_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY5'"!]
                [!VAR "eDmaPriority5_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY6'"!]
                [!VAR "eDmaPriority6_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY7'"!]
                [!VAR "eDmaPriority7_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY8'"!]
                [!VAR "eDmaPriority8_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY9'"!]
                [!VAR "eDmaPriority9_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY10'"!]
                [!VAR "eDmaPriority10_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY11'"!]
                [!VAR "eDmaPriority11_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY12'"!]
                [!VAR "eDmaPriority12_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY13'"!]
                [!VAR "eDmaPriority13_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY14'"!]
                [!VAR "eDmaPriority14_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmachPriority_temp = 'EDMA_CHN_PRIORITY15'"!]
                [!VAR "eDmaPriority15_temp" = "num:i(1)"!]
            [!ENDIF!] 
        [!ELSE!]
            .isUsed = FALSE,
            [!IF "$eDmaPriority0_temp = num:i(0)"!]
                [!VAR "eDmachPriority_temp" = "'EDMA_CHN_PRIORITY0'"!]
                [!VAR "eDmaPriority0_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmaPriority1_temp = num:i(0)"!]
                [!VAR "eDmachPriority_temp" = "'EDMA_CHN_PRIORITY1'"!]
                [!VAR "eDmaPriority1_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmaPriority2_temp = num:i(0)"!]
                [!VAR "eDmachPriority_temp" = "'EDMA_CHN_PRIORITY2'"!]
                [!VAR "eDmaPriority2_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmaPriority3_temp = num:i(0)"!]
                [!VAR "eDmachPriority_temp" = "'EDMA_CHN_PRIORITY3'"!]
                [!VAR "eDmaPriority3_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmaPriority4_temp = num:i(0)"!]
                [!VAR "eDmachPriority_temp" = "'EDMA_CHN_PRIORITY4'"!]
                [!VAR "eDmaPriority4_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmaPriority5_temp = num:i(0)"!]
                [!VAR "eDmachPriority_temp" = "'EDMA_CHN_PRIORITY5'"!]
                [!VAR "eDmaPriority5_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmaPriority6_temp = num:i(0)"!]
                [!VAR "eDmachPriority_temp" = "'EDMA_CHN_PRIORITY6'"!]
                [!VAR "eDmaPriority6_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmaPriority7_temp = num:i(0)"!]
                [!VAR "eDmachPriority_temp" = "'EDMA_CHN_PRIORITY7'"!]
                [!VAR "eDmaPriority7_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmaPriority8_temp = num:i(0)"!]
                [!VAR "eDmachPriority_temp" = "'EDMA_CHN_PRIORITY8'"!]
                [!VAR "eDmaPriority8_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmaPriority9_temp = num:i(0)"!]
                [!VAR "eDmachPriority_temp" = "'EDMA_CHN_PRIORITY9'"!]
                [!VAR "eDmaPriority9_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmaPriority10_temp = num:i(0)"!]
                [!VAR "eDmachPriority_temp" = "'EDMA_CHN_PRIORITY10'"!]
                [!VAR "eDmaPriority10_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmaPriority11_temp = num:i(0)"!]
                [!VAR "eDmachPriority_temp" = "'EDMA_CHN_PRIORITY11'"!]
                [!VAR "eDmaPriority11_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmaPriority12_temp = num:i(0)"!]
                [!VAR "eDmachPriority_temp" = "'EDMA_CHN_PRIORITY12'"!]
                [!VAR "eDmaPriority12_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmaPriority13_temp = num:i(0)"!]
                [!VAR "eDmachPriority_temp" = "'EDMA_CHN_PRIORITY13'"!]
                [!VAR "eDmaPriority13_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmaPriority14_temp = num:i(0)"!]
                [!VAR "eDmachPriority_temp" = "'EDMA_CHN_PRIORITY14'"!]
                [!VAR "eDmaPriority14_temp" = "num:i(1)"!]
            [!ELSEIF "$eDmaPriority15_temp = num:i(0)"!]
                [!VAR "eDmachPriority_temp" = "'EDMA_CHN_PRIORITY15'"!]
                [!VAR "eDmaPriority15_temp" = "num:i(1)"!]
            [!ENDIF!]
            .chPriority = [!"$eDmachPriority_temp"!]
        [!ENDIF!]
        
        [!ENDINDENT!]
    },
    [!ENDINDENT!]
    [!ENDFOR!]
};

CONST(EDma_ConfigType, EDMA_CONST) EDma_Config =
{
    .pEdma_DeviceConfig = dmaconfigure_InitConfig,
    .pEdma_ChStateArray = {
[!SELECT "eDmaConfigSet"!]
    [!INDENT "8"!]
        [!LOOP "eDmaChannelConfig/*"!]
            &[!"@name"!]_State,
        [!ENDLOOP!]
    [!ENDINDENT!]
[!ENDSELECT!]
    },
    .pEdma_ChanelConfig = {
[!SELECT "eDmaConfigSet"!]
    [!INDENT "8"!]
        [!LOOP "eDmaChannelConfig/*"!]
            &[!"@name"!]_Config,
        [!ENDLOOP!]
    [!ENDINDENT!]
[!ENDSELECT!]
    },
    .u32Edma_ChanelCnt = [!"num:i(count(eDmaConfigSet/eDmaChannelConfig/*))"!]U,
    .pEdma_ChPriorityCfgs = dmaChPriorityCfgs
};

#ifdef __cplusplus
}
#endif