/****************************************************************************
*
* Copyright (c) 2023  C*Core -   All Rights Reserved
*
* THIS SOFTWARE IS DISTRIBUTED "AS IS," AND ALL WARRANTIES ARE DISCLAIMED,
* INCLUDING MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
*
*   Project              : AUTOSAR 4.4.0 MCAL
*   Platform             : PowerPC
*   Peripheral           :
*   Dependencies         :
*
*   Autosar Version      : 4.4.0
*   Autosar Revision     : ASR_REL_4_4_REV_0000
*   Autosar Conf.Variant :
*   SW Version           :
*   Build Version        :
*
*****************************************************************************/

/**
*   @file    Gpt_Irq.c
*   @version 1.0.1
*
*      AUTOSAR 4.4.0 - Common Level Driver source file.
*    Autosar layer of Gpt MCAL driver.
*
*   @addtogroup Gpt
*   @{
*/
#ifdef __cplusplus
extern "C"{
#endif

/*==============================================INCLUDE FILES=======================================*/
#include "Gpt_Irq.h"
#include "Gpt_Stm_LLDriver.h"
#if ( defined(CCFC3012PT))
#include "Gpt_Gtm_LLDriver.h"
#endif
#include "Gpt_Pit_LLDriver.h"
#include "Gpt_AutoSar_Wrapper.h"

/*=====================================SOURCE FILE VERSION INFORMATION==============================*/

#define GPT_VENDOR_ID_C                 176
#define GPT_AR_MAJOR_VER_C              4
#define GPT_AR_MINOR_VER_C              4
#define GPT_AR_PATCH_VER_C              0
#define GPT_SW_MAJOR_VER_C              1
#define GPT_SW_MINOR_VER_C              0
#define GPT_SW_PATCH_VER_C              1

/*============================================FILE VERSION CHECKS===================================*/

/* Check if current file and GPT header file are of the same vendor */
#if (GPT_VENDOR_ID_C != GPT_VENDOR_ID)
#error "NON-MATCHED DATA : GPT_VENDOR_ID"
#endif

/* Check if current file and GPT header file are of the same Autosar version */
#if (GPT_AR_MAJOR_VER_C != GPT_CFG_AR_MAJOR_VER)
#error "NON-MATCHED DATA : GPT_CFG_AR_MAJOR_VER"
#endif
#if (GPT_AR_MINOR_VER_C != GPT_CFG_AR_MINOR_VER)
#error "NON-MATCHED DATA : GPT_CFG_AR_MINOR_VER"
#endif
#if (GPT_AR_PATCH_VER_C != GPT_CFG_AR_PATCH_VER)
#error "NON-MATCHED DATA : GPT_CFG_AR_PATCH_VER"
#endif

/* Check if current file and GPT header file are of the same Software version */
#if (GPT_SW_MAJOR_VER_C != GPT_CFG_SW_MAJOR_VER)
#error "NON-MATCHED DATA : GPT_CFG_SW_MAJOR_VER"
#endif
#if (GPT_SW_MINOR_VER_C != GPT_CFG_SW_MINOR_VER)
#error "NON-MATCHED DATA : GPT_CFG_SW_MINOR_VER"
#endif
#if (GPT_SW_PATCH_VER_C != GPT_CFG_SW_PATCH_VER)
#error "NON-MATCHED DATA : GPT_CFG_SW_PATCH_VER"
#endif


/*=================================================CONSTANTS========================================*/

/*===========================================VARIABLE DECLARATIONS==================================*/

#if ( defined(CCFC3007PT) || defined(CCFC3008PT))
extern P2VAR(st_GPT_GTM_TOM_tag, AUTOMATIC,GPT_APPL_DATA) g_GPT_GTM_TOM_Base[5U];
#endif
/*============================================DEFINES AND MACROS====================================*/

/*===================================================ENUMS==========================================*/

/*=======================================STRUCTURES AND OTHER TYPEDEFS==============================*/

/*===============================================LOCAL FUNCTIONS====================================*/

/*==============================================GLOBAL FUNCTIONS====================================*/

/*======================================STM IRQ============================*/

FUNC(void, GPT_CODE) STM0_CH0_Handler(void)
{
   Gpt_Stm_IRQHandler(STM0, STM_Channel0);
}
FUNC(void, GPT_CODE) STM0_CH1_Handler(void)
{
   Gpt_Stm_IRQHandler(STM0, STM_Channel1);
}

FUNC(void, GPT_CODE) STM0_CH2_Handler(void)
{
   Gpt_Stm_IRQHandler(STM0, STM_Channel2);
}

FUNC(void, GPT_CODE) STM0_CH3_Handler(void)
{
   Gpt_Stm_IRQHandler(STM0, STM_Channel3);
}

FUNC(void, GPT_CODE) STM1_CH0_Handler(void)
{
   Gpt_Stm_IRQHandler(STM1, STM_Channel0);
}

FUNC(void, GPT_CODE) STM1_CH1_Handler(void)
{
   Gpt_Stm_IRQHandler(STM1, STM_Channel1);
}

FUNC(void, GPT_CODE) STM1_CH2_Handler(void)
{
   Gpt_Stm_IRQHandler(STM1, STM_Channel2);
}

FUNC(void, GPT_CODE) STM1_CH3_Handler(void)
{
   Gpt_Stm_IRQHandler(STM1, STM_Channel3);
}

FUNC(void, GPT_CODE) STM2_CH0_Handler(void)
{
   Gpt_Stm_IRQHandler(STM2, STM_Channel0);
}

FUNC(void, GPT_CODE) STM2_CH1_Handler(void)
{
   Gpt_Stm_IRQHandler(STM2, STM_Channel1);
}

FUNC(void, GPT_CODE) STM2_CH2_Handler(void)
{
   Gpt_Stm_IRQHandler(STM2, STM_Channel2);
}

FUNC(void, GPT_CODE) STM2_CH3_Handler(void)
{
   Gpt_Stm_IRQHandler(STM2, STM_Channel3);
}

FUNC(void, GPT_CODE) STM3_CH0_Handler(void)
{
   Gpt_Stm_IRQHandler(STM3, STM_Channel0);
}

FUNC(void, GPT_CODE) STM3_CH1_Handler(void)
{
   Gpt_Stm_IRQHandler(STM3, STM_Channel1);
}

FUNC(void, GPT_CODE) STM3_CH2_Handler(void)
{
   Gpt_Stm_IRQHandler(STM3, STM_Channel2);
}

FUNC(void, GPT_CODE) STM3_CH3_Handler(void)
{
   Gpt_Stm_IRQHandler(STM3, STM_Channel3);
}
FUNC(void, GPT_CODE) STM4_CH0_Handler(void)
{
   Gpt_Stm_IRQHandler(STM4, STM_Channel0);
}

FUNC(void, GPT_CODE) STM4_CH1_Handler(void)
{
   Gpt_Stm_IRQHandler(STM4, STM_Channel1);
}

FUNC(void, GPT_CODE) STM4_CH2_Handler(void)
{
   Gpt_Stm_IRQHandler(STM4, STM_Channel2);
}

FUNC(void, GPT_CODE) STM4_CH3_Handler(void)
{
   Gpt_Stm_IRQHandler(STM4, STM_Channel3);
}

FUNC(void, GPT_CODE) STM5_CH0_Handler(void)
{
   Gpt_Stm_IRQHandler(STM5, STM_Channel0);
}

FUNC(void, GPT_CODE) STM5_CH1_Handler(void)
{
   Gpt_Stm_IRQHandler(STM5, STM_Channel1);
}

FUNC(void, GPT_CODE) STM5_CH2_Handler(void)
{
   Gpt_Stm_IRQHandler(STM5, STM_Channel2);
}

FUNC(void, GPT_CODE) STM5_CH3_Handler(void)
{
   Gpt_Stm_IRQHandler(STM5, STM_Channel3);
}
/*======================================PIT IRQ============================*/
FUNC(void, GPT_CODE) PIT0_CH0_ISR(void)
{
   Gpt_Pit_IRQHandler(PIT0, PIT_Channel0);
}

FUNC(void, GPT_CODE) PIT0_CH1_ISR(void)
{
   Gpt_Pit_IRQHandler(PIT0, PIT_Channel1);
}

FUNC(void, GPT_CODE) PIT0_CH2_ISR(void)
{
   Gpt_Pit_IRQHandler(PIT0, PIT_Channel2);
}

FUNC(void, GPT_CODE) PIT0_CH3_ISR(void)
{
   Gpt_Pit_IRQHandler(PIT0, PIT_Channel3);
}

FUNC(void, GPT_CODE) PIT0_CH4_ISR(void)
{
   Gpt_Pit_IRQHandler(PIT0, PIT_Channel4);
}

FUNC(void, GPT_CODE) PIT0_CH5_ISR(void)
{
   Gpt_Pit_IRQHandler(PIT0, PIT_Channel5);
}

FUNC(void, GPT_CODE) PIT0_CH6_ISR(void)
{
   Gpt_Pit_IRQHandler(PIT0, PIT_Channel6);
}

FUNC(void, GPT_CODE) PIT0_CH7_ISR(void)
{
   Gpt_Pit_IRQHandler(PIT0, PIT_Channel7);
}

FUNC(void, GPT_CODE) PIT1_CH0_ISR(void)
{
   Gpt_Pit_IRQHandler(PIT1, PIT_Channel0);
}

FUNC(void, GPT_CODE) PIT1_CH1_ISR(void)
{
   Gpt_Pit_IRQHandler(PIT1, PIT_Channel1);
}

FUNC(void, GPT_CODE) RTI_ISR(void)
{
   Gpt_Pit_IRQHandler(PIT0, PIT_RTI);
}


/*======================================TOM IRQ============================*/
#if ( defined(CCFC3007PT) || defined(CCFC3008PT)|| defined(CCFC3012PT))
FUNC(void, GPT_CODE) TOM0_CH0_CH1_ISR(void)
{
	if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH0].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH0].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM0, GPT_GTM_TOM_CH0);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH1].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH1].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM0, GPT_GTM_TOM_CH1);
		}
	}
}

FUNC(void, GPT_CODE) TOM0_CH2_CH3_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH2].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH2].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM0, GPT_GTM_TOM_CH2);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH3].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH3].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM0, GPT_GTM_TOM_CH3);
		}
	}
}

FUNC(void, GPT_CODE) TOM0_CH4_CH5_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH4].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH4].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM0, GPT_GTM_TOM_CH4);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH5].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH5].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM0, GPT_GTM_TOM_CH5);
		}
	}
}

FUNC(void, GPT_CODE) TOM0_CH6_CH7_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH6].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH6].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM0, GPT_GTM_TOM_CH6);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH7].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH7].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM0, GPT_GTM_TOM_CH7);
		}
	}
}

FUNC(void, GPT_CODE) TOM0_CH8_CH9_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH8].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH8].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM0, GPT_GTM_TOM_CH8);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH9].IRQ_EN.R  != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH9].IRQ_NOTIFY.R  == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM0, GPT_GTM_TOM_CH9);
		}
	}
}

FUNC(void, GPT_CODE) TOM0_CH10_CH11_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH10].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH10].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM0, GPT_GTM_TOM_CH10);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH11].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH11].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM0, GPT_GTM_TOM_CH11);
		}
	}
}

FUNC(void, GPT_CODE) TOM0_CH12_CH13_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH12].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH12].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM0, GPT_GTM_TOM_CH12);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH13].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH13].IRQ_NOTIFY.R  == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM0, GPT_GTM_TOM_CH13);
		}
	}
}

FUNC(void, GPT_CODE) TOM0_CH14_CH15_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH14].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH14].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM0, GPT_GTM_TOM_CH14);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH15].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM0].TOM.CH[GPT_GTM_TOM_CH15].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM0, GPT_GTM_TOM_CH15);
		}
	}
}
#include "console.h"

/* GPT GTM TOM1 */
FUNC(void, GPT_CODE) TOM1_CH0_CH1_ISR(void)
{
	if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH0].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH0].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM1, GPT_GTM_TOM_CH0);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH1].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH1].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM1, GPT_GTM_TOM_CH1);
		}
	}
}

FUNC(void, GPT_CODE) TOM1_CH2_CH3_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH2].IRQ_EN.R!= 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH2].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM1, GPT_GTM_TOM_CH2);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH3].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH3].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM1, GPT_GTM_TOM_CH3);
		}
	}
}

FUNC(void, GPT_CODE) TOM1_CH4_CH5_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH4].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH4].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM1, GPT_GTM_TOM_CH4);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH5].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH5].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM1, GPT_GTM_TOM_CH5);
		}
	}
}

FUNC(void, GPT_CODE) TOM1_CH6_CH7_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH6].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH6].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM1, GPT_GTM_TOM_CH6);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH7].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH7].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM1, GPT_GTM_TOM_CH7);
		}
	}
}

FUNC(void, GPT_CODE) TOM1_CH8_CH9_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH8].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH8].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM1, GPT_GTM_TOM_CH8);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH9].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH9].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM1, GPT_GTM_TOM_CH9);
		}
	}
}

FUNC(void, GPT_CODE) TOM1_CH10_CH11_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH10].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH10].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM1, GPT_GTM_TOM_CH10);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH11].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH11].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM1, GPT_GTM_TOM_CH11);
		}
	}
}

FUNC(void, GPT_CODE) TOM1_CH12_CH13_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH12].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH12].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM1, GPT_GTM_TOM_CH12);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH13].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH13].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM1, GPT_GTM_TOM_CH13);
		}
	}
}

FUNC(void, GPT_CODE) TOM1_CH14_CH15_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH14].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH14].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM1, GPT_GTM_TOM_CH14);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH15].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM1].TOM.CH[GPT_GTM_TOM_CH15].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM1, GPT_GTM_TOM_CH15);
		}
	}
}

/* GPT GTM TOM2 */
FUNC(void, GPT_CODE) TOM2_CH0_CH1_ISR(void)
{
	if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH0].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH0].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM2, GPT_GTM_TOM_CH0);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH1].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH1].IRQ_NOTIFY.R== 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM2, GPT_GTM_TOM_CH1);
		}
	}
}

FUNC(void, GPT_CODE) TOM2_CH2_CH3_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH2].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH2].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM2, GPT_GTM_TOM_CH2);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH3].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH3].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM2, GPT_GTM_TOM_CH3);
		}
	}
}

FUNC(void, GPT_CODE) TOM2_CH4_CH5_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH4].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH4].IRQ_NOTIFY.R== 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM2, GPT_GTM_TOM_CH4);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH5].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH5].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM2, GPT_GTM_TOM_CH5);
		}
	}
}

FUNC(void, GPT_CODE) TOM2_CH6_CH7_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH6].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH6].IRQ_NOTIFY.R== 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM2, GPT_GTM_TOM_CH6);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH7].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH7].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM2, GPT_GTM_TOM_CH7);
		}
	}
}

FUNC(void, GPT_CODE) TOM2_CH8_CH9_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH8].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH8].IRQ_NOTIFY.R== 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM2, GPT_GTM_TOM_CH8);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH9].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH9].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM2, GPT_GTM_TOM_CH9);
		}
	}
}

FUNC(void, GPT_CODE) TOM2_CH10_CH11_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH10].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH10].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM2, GPT_GTM_TOM_CH10);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH11].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH11].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM2, GPT_GTM_TOM_CH11);
		}
	}
}

FUNC(void, GPT_CODE) TOM2_CH12_CH13_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH12].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH12].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM2, GPT_GTM_TOM_CH12);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH13].IRQ_EN.R!= 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH13].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM2, GPT_GTM_TOM_CH13);
		}
	}
}

FUNC(void, GPT_CODE) TOM2_CH14_CH15_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH14].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH14].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM2, GPT_GTM_TOM_CH14);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH15].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM2].TOM.CH[GPT_GTM_TOM_CH15].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM2, GPT_GTM_TOM_CH15);
		}
	}
}

/* GPT GTM TOM3 */
FUNC(void, GPT_CODE) TOM3_CH0_CH1_ISR(void)
{
	if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH0].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH0].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM3, GPT_GTM_TOM_CH0);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH1].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH1].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM3, GPT_GTM_TOM_CH1);
		}
	}
}

FUNC(void, GPT_CODE) TOM3_CH2_CH3_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH2].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH2].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM3, GPT_GTM_TOM_CH2);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH3].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH3].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM3, GPT_GTM_TOM_CH3);
		}
	}
}

FUNC(void, GPT_CODE) TOM3_CH4_CH5_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH4].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH4].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM3, GPT_GTM_TOM_CH4);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH5].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH5].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM3, GPT_GTM_TOM_CH5);
		}
	}
}

FUNC(void, GPT_CODE) TOM3_CH6_CH7_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH6].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH6].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM3, GPT_GTM_TOM_CH6);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH7].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH7].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM3, GPT_GTM_TOM_CH7);
		}
	}
}

FUNC(void, GPT_CODE) TOM3_CH8_CH9_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH8].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH8].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM3, GPT_GTM_TOM_CH8);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH9].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH9].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM3, GPT_GTM_TOM_CH9);
		}
	}
}

FUNC(void, GPT_CODE) TOM3_CH10_CH11_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH10].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH10].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM3, GPT_GTM_TOM_CH10);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH11].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH11].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM3, GPT_GTM_TOM_CH11);
		}
	}
}

FUNC(void, GPT_CODE) TOM3_CH12_CH13_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH12].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH12].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM3, GPT_GTM_TOM_CH12);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH13].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH13].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM3, GPT_GTM_TOM_CH13);
		}
	}
}

FUNC(void, GPT_CODE) TOM3_CH14_CH15_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH14].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH14].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM3, GPT_GTM_TOM_CH14);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH15].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM3].TOM.CH[GPT_GTM_TOM_CH15].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM3, GPT_GTM_TOM_CH15);
		}
	}
}

/* GPT_GTM_TOM4 */
FUNC(void, GPT_CODE) TOM4_CH0_CH1_ISR(void)
{
	if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH0].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH0].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM4, GPT_GTM_TOM_CH0);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH1].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH1].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM4, GPT_GTM_TOM_CH1);
		}
	}
}

FUNC(void, GPT_CODE) TOM4_CH2_CH3_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH2].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH2].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM4, GPT_GTM_TOM_CH2);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH3].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH3].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM4, GPT_GTM_TOM_CH3);
		}
	}
}

FUNC(void, GPT_CODE) TOM4_CH4_CH5_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH4].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH4].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM4, GPT_GTM_TOM_CH4);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH5].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH5].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM4, GPT_GTM_TOM_CH5);
		}
	}
}

FUNC(void, GPT_CODE) TOM4_CH6_CH7_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH6].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH6].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM4, GPT_GTM_TOM_CH6);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH7].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH7].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM4, GPT_GTM_TOM_CH7);
		}
	}
}

FUNC(void, GPT_CODE) TOM4_CH8_CH9_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH8].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH8].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM4, GPT_GTM_TOM_CH8);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH9].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH9].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM4, GPT_GTM_TOM_CH9);
		}
	}
}

FUNC(void, GPT_CODE) TOM4_CH10_CH11_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH10].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH10].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM4, GPT_GTM_TOM_CH10);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH11].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH11].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM4, GPT_GTM_TOM_CH11);
		}
	}
}

FUNC(void, GPT_CODE) TOM4_CH12_CH13_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH12].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH12].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM4, GPT_GTM_TOM_CH12);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH13].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH13].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM4, GPT_GTM_TOM_CH13);
		}
	}
}

FUNC(void, GPT_CODE) TOM4_CH14_CH15_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH14].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH14].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM4, GPT_GTM_TOM_CH14);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH15].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM4].TOM.CH[GPT_GTM_TOM_CH15].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM4, GPT_GTM_TOM_CH15);
		}
	}
}

/* GPT_GTM_TOM5 */
FUNC(void, GPT_CODE) TOM5_CH0_CH1_ISR(void)
{
	if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH0].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH0].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM5, GPT_GTM_TOM_CH0);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH1].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH1].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM5, GPT_GTM_TOM_CH1);
		}
	}
}

FUNC(void, GPT_CODE) TOM5_CH2_CH3_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH2].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH2].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM5, GPT_GTM_TOM_CH2);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH3].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH3].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM5, GPT_GTM_TOM_CH3);
		}
	}
}

FUNC(void, GPT_CODE) TOM5_CH4_CH5_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH4].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH4].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM5, GPT_GTM_TOM_CH4);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH5].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH5].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM5, GPT_GTM_TOM_CH5);
		}
	}
}

FUNC(void, GPT_CODE) TOM5_CH6_CH7_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH6].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH6].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM5, GPT_GTM_TOM_CH6);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH7].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH7].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM5, GPT_GTM_TOM_CH7);
		}
	}
}

FUNC(void, GPT_CODE) TOM5_CH8_CH9_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH8].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH8].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM5, GPT_GTM_TOM_CH8);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH9].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH9].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM5, GPT_GTM_TOM_CH9);
		}
	}
}

FUNC(void, GPT_CODE) TOM5_CH10_CH11_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH10].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH10].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM5, GPT_GTM_TOM_CH10);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH11].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH11].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM5, GPT_GTM_TOM_CH11);
		}
	}
}

FUNC(void, GPT_CODE) TOM5_CH12_CH13_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH12].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH12].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM5, GPT_GTM_TOM_CH12);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH13].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH13].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM5, GPT_GTM_TOM_CH13);
		}
	}
}

FUNC(void, GPT_CODE) TOM5_CH14_CH15_ISR(void)
{
    if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH14].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH14].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM5, GPT_GTM_TOM_CH14);
		}
	}
	if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH15].IRQ_EN.R != 0u)
	{
		if(GTM4.GLS[GPT_GTM_TOM5].TOM.CH[GPT_GTM_TOM_CH15].IRQ_NOTIFY.R == 1u)
		{
			GPT_TOM_LLD_IRQHandler(GPT_GTM_TOM5, GPT_GTM_TOM_CH15);
		}
	}
}

#endif

FUNC(void,GPT_CODE) Gpt_Stm_Callback_From_IRQ(VAR(Gpt_ChannelType, AUTOMATIC) Gpt_Channel)
{
    /* Process callback */
    Gpt_ProcessCommonIrq(Gpt_Channel);
}

FUNC(void, GPT_CODE) Gpt_Pit_Callback_From_IRQ(VAR(Gpt_ChannelType, AUTOMATIC) Gpt_Channel)
{
    /* Process callback */
    Gpt_ProcessCommonIrq(Gpt_Channel);
}

#if ( defined(CCFC3007PT) || defined(CCFC3008PT)|| defined(CCFC3012PT))
FUNC(void,GPT_CODE) Gpt_Gtm_Callback_From_IRQ(VAR(Gpt_ChannelType, AUTOMATIC) Gpt_Channel)
{
    /* Process callback */
    Gpt_ProcessCommonIrq(Gpt_Channel);
}
#endif
FUNC(void,GPT_CODE) Gpt_Rtc_Callback_From_IRQ(VAR(Gpt_ChannelType, AUTOMATIC) Gpt_Channel)
{
	/* Process callback */
	Gpt_ProcessCommonIrq(Gpt_Channel);

}



#ifdef __cplusplus
}
#endif
