#ifndef GMAC_REG_H_
#define GMAC_REG_H_
/**************************************************************************/
/*                              Module: GMAC                        */
/**************************************************************************/
struct GMAC_tag {
    union {
        vuint32_t R;
        struct {
            vuint32_t ARPEN:1;
            vuint32_t SARC:3;
            vuint32_t IPC:1;
            vuint32_t IPG:3;
            vuint32_t GPSLCE:1;
            vuint32_t S2KP:1;
            vuint32_t CST:1;
            vuint32_t ACS:1;
            vuint32_t WD:1;
            vuint32_t BE:1;
            vuint32_t JD:1;
            vuint32_t JE:1;
            vuint32_t PS:1;
            vuint32_t FES:1;
            vuint32_t DM:1;
            vuint32_t LM:1;
            vuint32_t ECRSFD:1;
            vuint32_t DO:1;
            vuint32_t DCRS:1;
            vuint32_t DR:1;
            vuint32_t unused_0:1;
            vuint32_t BL:2;
            vuint32_t DC:1;
            vuint32_t PRELEN:2;
            vuint32_t TE:1;
            vuint32_t RE:1;
        } B;
    } MAC_CONFIGURATION;

    union {
        vuint32_t R;
        struct {
            vuint32_t SYS_CLK_SEL:1;
            vuint32_t APDIM:1;
            vuint32_t EIPG:5;
            vuint32_t EIPGEN:1;
            vuint32_t unused_1:1;
            vuint32_t HDSMS:3;
            vuint32_t PDC:1;
            vuint32_t USP:1;
            vuint32_t SPEN:1;
            vuint32_t DCRCC:1;
            vuint32_t GREFCLK_TXCLK_SEL:2;
            vuint32_t GPSL:14;
        } B;
    } MAC_EXT_CONFIGURATION;

    union {
        vuint32_t R;
        struct {
            vuint32_t RA:1;
            vuint32_t unused_2:9;
            vuint32_t DNTU:1;
            vuint32_t IPFE:1;
            vuint32_t unused_1:3;
            vuint32_t VTFE:1;
            vuint32_t unused_0:5;
            vuint32_t HPF:1;
            vuint32_t SAF:1;
            vuint32_t SAIF:1;
            vuint32_t PCF:2;
            vuint32_t DBF:1;
            vuint32_t PM:1;
            vuint32_t DAIF:1;
            vuint32_t HMC:1;
            vuint32_t HUC:1;
            vuint32_t PR:1;
        } B;
    } MAC_PACKET_FILTER;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_3:7;
            vuint32_t PJE:1;
            vuint32_t unused_2:4;
            vuint32_t JTO:4;
            vuint32_t unused_1:7;
            vuint32_t PWE:1;
            vuint32_t unused_0:4;
            vuint32_t WTO:4;
        } B;
    } MAC_WD_JB_TIMEOUT;

    union {
        vuint32_t R;
        struct {
            vuint32_t HT31T0:32;
        } B;
    } MAC_HASH_TABLE_REG0;

    union {
        vuint32_t R;
        struct {
            vuint32_t HT63T32:32;
        } B;
    } MAC_HASH_TABLE_REG1;

    vuint8_t ADR_reserved0[56];

    union{
        union {
            vuint32_t R;
            struct {
                vuint32_t EIVLRXS:1;
                vuint32_t unused_2:1;
                vuint32_t EIVLS:2;
                vuint32_t ERIVLT:1;
                vuint32_t EDVLP:1;
                vuint32_t VTHM:1;
                vuint32_t EVLRXS:1;
                vuint32_t unused_1:1;
                vuint32_t EVLS:2;
                vuint32_t DOVLTC:1;
                vuint32_t ERSVLM:1;
                vuint32_t ESVL:1;
                vuint32_t VTIM:1;
                vuint32_t ETV:1;
                vuint32_t VL:16;
            } B;
        } MAC_VLAN_TAG;
        union {
            vuint32_t R;
            struct {
                vuint32_t EIVLRXS:1;
                vuint32_t unused_2:1;
                vuint32_t EIVLS:2;
                vuint32_t ERIVLT:1;
                vuint32_t EDVLP:1;
                vuint32_t VTHM:1;
                vuint32_t EVLRXS:1;
                vuint32_t unused_1:1;
                vuint32_t EVLS:2;
                vuint32_t DOVLTC:1;
                vuint32_t ERSVLM:1;
                vuint32_t ESVL:1;
                vuint32_t VTIM:1;
                vuint32_t ETV:1;
                vuint32_t unused_0:10;
                vuint32_t OFS:4;
                vuint32_t CT:1;
                vuint32_t OB:1;
            } B;
        } MAC_VLAN_TAG_CTRL;
    };

    union {
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:6;
                vuint32_t DMACHN:1;
                vuint32_t DMACHEN:1;
                vuint32_t unused_0:3;
                vuint32_t ERIVLT:1;
                vuint32_t ERSVLM:1;
                vuint32_t DOVLTC:1;
                vuint32_t EVT:1;
                vuint32_t VEN:1;
                vuint32_t VID:16;
            } B;
        } MAC_VLAN_TAG_DATA;
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:6;
                vuint32_t DMACHN:1;
                vuint32_t DMACHEN:1;
                vuint32_t unused_0:3;
                vuint32_t ERIVLT:1;
                vuint32_t ERSVLM:1;
                vuint32_t DOVLTC:1;
                vuint32_t ETV:1;
                vuint32_t VEN:1;
                vuint32_t VID:16;
            } B;
        } MAC_VLAN_TAG_FILTER0;
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:6;
                vuint32_t DMACHN:1;
                vuint32_t DMACHEN:1;
                vuint32_t unused_0:3;
                vuint32_t ERIVLT:1;
                vuint32_t ERSVLM:1;
                vuint32_t DOVLTC:1;
                vuint32_t ETV:1;
                vuint32_t VEN:1;
                vuint32_t VID:16;
            } B;
        } MAC_VLAN_TAG_FILTER1;
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:6;
                vuint32_t DMACHN:1;
                vuint32_t DMACHEN:1;
                vuint32_t unused_0:3;
                vuint32_t ERIVLT:1;
                vuint32_t ERSVLM:1;
                vuint32_t DOVLTC:1;
                vuint32_t ETV:1;
                vuint32_t VEN:1;
                vuint32_t VID:16;
            } B;
        } MAC_VLAN_TAG_FILTER2;
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:6;
                vuint32_t DMACHN:1;
                vuint32_t DMACHEN:1;
                vuint32_t unused_0:3;
                vuint32_t ERIVLT:1;
                vuint32_t ERSVLM:1;
                vuint32_t DOVLTC:1;
                vuint32_t ETV:1;
                vuint32_t VEN:1;
                vuint32_t VID:16;
            } B;
        } MAC_VLAN_TAG_FILTER3;
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:6;
                vuint32_t DMACHN:1;
                vuint32_t DMACHEN:1;
                vuint32_t unused_0:3;
                vuint32_t ERIVLT:1;
                vuint32_t ERSVLM:1;
                vuint32_t DOVLTC:1;
                vuint32_t ETV:1;
                vuint32_t VEN:1;
                vuint32_t VID:16;
            } B;
        } MAC_VLAN_TAG_FILTER4;
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:6;
                vuint32_t DMACHN:1;
                vuint32_t DMACHEN:1;
                vuint32_t unused_0:3;
                vuint32_t ERIVLT:1;
                vuint32_t ERSVLM:1;
                vuint32_t DOVLTC:1;
                vuint32_t ETV:1;
                vuint32_t VEN:1;
                vuint32_t VID:16;
            } B;
        } MAC_VLAN_TAG_FILTER5;
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:6;
                vuint32_t DMACHN:1;
                vuint32_t DMACHEN:1;
                vuint32_t unused_0:3;
                vuint32_t ERIVLT:1;
                vuint32_t ERSVLM:1;
                vuint32_t DOVLTC:1;
                vuint32_t ETV:1;
                vuint32_t VEN:1;
                vuint32_t VID:16;
            } B;
        } MAC_VLAN_TAG_FILTER6;
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:6;
                vuint32_t DMACHN:1;
                vuint32_t DMACHEN:1;
                vuint32_t unused_0:3;
                vuint32_t ERIVLT:1;
                vuint32_t ERSVLM:1;
                vuint32_t DOVLTC:1;
                vuint32_t ETV:1;
                vuint32_t VEN:1;
                vuint32_t VID:16;
            } B;
        } MAC_VLAN_TAG_FILTER7;
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:6;
                vuint32_t DMACHN:1;
                vuint32_t DMACHEN:1;
                vuint32_t unused_0:3;
                vuint32_t ERIVLT:1;
                vuint32_t ERSVLM:1;
                vuint32_t DOVLTC:1;
                vuint32_t ETV:1;
                vuint32_t VEN:1;
                vuint32_t VID:16;
            } B;
        } MAC_VLAN_TAG_FILTER8;
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:6;
                vuint32_t DMACHN:1;
                vuint32_t DMACHEN:1;
                vuint32_t unused_0:3;
                vuint32_t ERIVLT:1;
                vuint32_t ERSVLM:1;
                vuint32_t DOVLTC:1;
                vuint32_t ETV:1;
                vuint32_t VEN:1;
                vuint32_t VID:16;
            } B;
        } MAC_VLAN_TAG_FILTER9;
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:6;
                vuint32_t DMACHN:1;
                vuint32_t DMACHEN:1;
                vuint32_t unused_0:3;
                vuint32_t ERIVLT:1;
                vuint32_t ERSVLM:1;
                vuint32_t DOVLTC:1;
                vuint32_t ETV:1;
                vuint32_t VEN:1;
                vuint32_t VID:16;
            } B;
        } MAC_VLAN_TAG_FILTER10;
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:6;
                vuint32_t DMACHN:1;
                vuint32_t DMACHEN:1;
                vuint32_t unused_0:3;
                vuint32_t ERIVLT:1;
                vuint32_t ERSVLM:1;
                vuint32_t DOVLTC:1;
                vuint32_t ETV:1;
                vuint32_t VEN:1;
                vuint32_t VID:16;
            } B;
        } MAC_VLAN_TAG_FILTER11;
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:6;
                vuint32_t DMACHN:1;
                vuint32_t DMACHEN:1;
                vuint32_t unused_0:3;
                vuint32_t ERIVLT:1;
                vuint32_t ERSVLM:1;
                vuint32_t DOVLTC:1;
                vuint32_t ETV:1;
                vuint32_t VEN:1;
                vuint32_t VID:16;
            } B;
        } MAC_VLAN_TAG_FILTER12;
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:6;
                vuint32_t DMACHN:1;
                vuint32_t DMACHEN:1;
                vuint32_t unused_0:3;
                vuint32_t ERIVLT:1;
                vuint32_t ERSVLM:1;
                vuint32_t DOVLTC:1;
                vuint32_t ETV:1;
                vuint32_t VEN:1;
                vuint32_t VID:16;
            } B;
        } MAC_VLAN_TAG_FILTER13;
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:6;
                vuint32_t DMACHN:1;
                vuint32_t DMACHEN:1;
                vuint32_t unused_0:3;
                vuint32_t ERIVLT:1;
                vuint32_t ERSVLM:1;
                vuint32_t DOVLTC:1;
                vuint32_t ETV:1;
                vuint32_t VEN:1;
                vuint32_t VID:16;
            } B;
        } MAC_VLAN_TAG_FILTER14;
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:6;
                vuint32_t DMACHN:1;
                vuint32_t DMACHEN:1;
                vuint32_t unused_0:3;
                vuint32_t ERIVLT:1;
                vuint32_t ERSVLM:1;
                vuint32_t DOVLTC:1;
                vuint32_t ETV:1;
                vuint32_t VEN:1;
                vuint32_t VID:16;
            } B;
        } MAC_VLAN_TAG_FILTER15;
    };

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:16;
            vuint32_t VLHT:16;
        } B;
    } MAC_VLAN_HASH_TABLE;

    vuint8_t ADR_reserved17[4];

    union {
        union {
            vuint32_t R;
            struct {
                vuint32_t BUSY:1;
                vuint32_t RDWR:1;
                vuint32_t unused_1:5;
                vuint32_t ADDR:1;
                vuint32_t unused_0:2;
                vuint32_t CBTI:1;
                vuint32_t VLTI:1;
                vuint32_t CSVL:1;
                vuint32_t VLP:1;
                vuint32_t VLC:2;
                vuint32_t VLT:16;
            } B;
        } MAC_VLAN_INCL;
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:12;
                vuint32_t CSVL:1;
                vuint32_t unused_0:3;
                vuint32_t VLT:16;
            } B;
        } MAC_VLAN_INCL0;
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:12;
                vuint32_t CSVL:1;
                vuint32_t unused_0:3;
                vuint32_t VLT:16;
            } B;
        } MAC_VLAN_INCL1;
    };

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:11;
            vuint32_t VLTI:1;
            vuint32_t CSVL:1;
            vuint32_t VLP:1;
            vuint32_t VLC:2;
            vuint32_t VLT:16;
        } B;
    } MAC_INNER_VLAN_INCL;

    vuint8_t ADR_reserved20[8];

    union {
        vuint32_t R;
        struct {
            vuint32_t PT:16;
            vuint32_t unused_1:8;
            vuint32_t DZPQ:1;
            vuint32_t PLT:3;
            vuint32_t unused_0:2;
            vuint32_t TFE:1;
            vuint32_t FCB_BPA:1;
        } B;
    } MAC_Q0_TX_FLOW_CTRL;

    vuint8_t ADR_reserved21[28];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:23;
            vuint32_t PFCE:1;
            vuint32_t unused_0:6;
            vuint32_t UP:1;
            vuint32_t RFE:1;
        } B;
    } MAC_RX_FLOW_CTRL;

    union {
        vuint32_t R;
        struct {
            vuint32_t UDC:1;
            vuint32_t unused_2:13;
            vuint32_t VFFQ:1;
            vuint32_t VFFQE:1;
            vuint32_t unused_1:6;
            vuint32_t MFFQ:1;
            vuint32_t MFFQE:1;
            vuint32_t unused_0:6;
            vuint32_t UFFQ:1;
            vuint32_t UFFQE:1;
        } B;
    } MAC_RXQ_CTRL4;

    vuint8_t ADR_reserved22[8];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:16;
            vuint32_t RXQ7EN:2;
            vuint32_t RXQ6EN:2;
            vuint32_t RXQ5EN:2;
            vuint32_t RXQ4EN:2;
            vuint32_t RXQ3EN:2;
            vuint32_t RXQ2EN:2;
            vuint32_t RXQ1EN:2;
            vuint32_t RXQ0EN:2;
        } B;
    } MAC_RXQ_CTRL0;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_6:2;
            vuint32_t TBRQE:1;
            vuint32_t OMCBCQ:1;
            vuint32_t unused_5:1;
            vuint32_t FPQC:3;
            vuint32_t TPQC:2;
            vuint32_t TACPQE:1;
            vuint32_t MCBCQEN:1;
            vuint32_t unused_4:1;
            vuint32_t MCBCQ:3;
            vuint32_t unused_3:1;
            vuint32_t UPQ:3;
            vuint32_t unused_2:1;
            vuint32_t DCBCPQ:3;
            vuint32_t unused_1:1;
            vuint32_t PTPQ:3;
            vuint32_t unused_0:1;
            vuint32_t AVCPQ:3;
        } B;
    } MAC_RXQ_CTRL1;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:16;
            vuint32_t PSRQ1:8;
            vuint32_t PSRQ0:8;
        } B;
    } MAC_RXQ_CTRL2;

    union {
		vuint32_t R;
		struct {
			vuint32_t PSRQ7:8;
			vuint32_t PSRQ6:8;
			vuint32_t PSRQ5:8;
			vuint32_t PSRQ4:8;
		} B;
	} MAC_RXQ_CTRL3;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_3:8;
            vuint32_t PCIS:1;
            vuint32_t unused_2:2;
            vuint32_t MFRIS:1;
            vuint32_t MFTIS:1;
            vuint32_t MDIOIS:1;
            vuint32_t FPEIS:1;
            vuint32_t unused_1:1;
            vuint32_t GPIIS:1;
            vuint32_t RXSTSIS:1;
            vuint32_t TXSTSIS:1;
            vuint32_t TSIS:1;
            vuint32_t MMCRXIPIS:1;
            vuint32_t MMCTXIS:1;
            vuint32_t MMCRXIS:1;
            vuint32_t MMCIS:1;
            vuint32_t unused_0:2;
            vuint32_t LPIIS:1;
            vuint32_t PMTIS:1;
            vuint32_t PHYIS:1;
            vuint32_t PCSANCIS:1;
            vuint32_t PCSLCHGIS:1;
            vuint32_t PGSMIIIS:1;
        } B;
    } MAC_INTERRUPT_STATUS;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_3:13;
            vuint32_t MDIOIE:1;
            vuint32_t FPEIE:1;
            vuint32_t unused_2:2;
            vuint32_t RXSTSIE:1;
            vuint32_t TXSTSIE:1;
            vuint32_t TSIE:1;
            vuint32_t unused_1:6;
            vuint32_t LPIIE:1;
            vuint32_t PMTIE:1;
            vuint32_t PHYIE:1;
            vuint32_t PCSANCIE:1;
            vuint32_t PCSLCHGIE:1;
            vuint32_t PGSMIIIE:1;
        } B;
    } MAC_INTERRUPT_ENABLE;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:23;
            vuint32_t RWT:1;
            vuint32_t unused_0:2;
            vuint32_t EXCOL:1;
            vuint32_t LCOL:1;
            vuint32_t EXDEF:1;
            vuint32_t LCARR:1;
            vuint32_t NCARR:1;
            vuint32_t TJT:1;
        } B;
    } MAC_RX_TX_STATUS;

    vuint8_t ADR_reserved24[4];

    union {
        vuint32_t R;
        struct {
            vuint32_t RWKFILTRST:1;
            vuint32_t unused_3:2;
            vuint32_t RWKPTR:5;
            vuint32_t unused_2:13;
            vuint32_t RWKPFE:1;
            vuint32_t GLBLUCAST:1;
            vuint32_t unused_1:2;
            vuint32_t RWKPRCVD:1;
            vuint32_t MGKPRCVD:1;
            vuint32_t unused_0:2;
            vuint32_t RWKPKTEN:1;
            vuint32_t MGKPKTEN:1;
            vuint32_t PWRDWN:1;
        } B;
    } MAC_PMT_CONTROL_STATUS;

    union {
        union {
            vuint32_t R;
            struct {
                vuint32_t WKUPFRMFTR:32;
            } B;
        } MAC_RWK_PACKET_FILTER;
        union {
            vuint32_t R;
            struct {
                vuint32_t FILTER0_BYTE_MASK:32;
            } B;
        } RWK_FILTER0_BYTE_MASK;
        union {
            vuint32_t R;
            struct {
                vuint32_t FILTER1_BYTE_MASK:32;
            } B;
        } RWK_FILTER1_BYTE_MASK;
        union {
            vuint32_t R;
            struct {
                vuint32_t FILTER2_BYTE_MASK:32;
            } B;
        } RWK_FILTER2_BYTE_MASK;
        union {
            vuint32_t R;
            struct {
                vuint32_t FILTER3_BYTE_MASK:32;
            } B;
        } RWK_FILTER3_BYTE_MASK;
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_3:4;
                vuint32_t FILTER3_COMMAND:4;
                vuint32_t unused_2:4;
                vuint32_t FILTER2_COMMAND:4;
                vuint32_t unused_1:4;
                vuint32_t FILTER1_COMMAND:4;
                vuint32_t unused_0:4;
                vuint32_t FILTER0_COMMAND:4;
            } B;
        } RWK_FILTER0123_COMMAND;
        union {
            vuint32_t R;
            struct {
                vuint32_t FILTER3_OFFSET:8;
                vuint32_t FILTER2_OFFSET:8;
                vuint32_t FILTER1_OFFSET:8;
                vuint32_t FILTER0_OFFSET:8;
            } B;
        } RWK_FILTER0123_OFFSET;
        union {
            vuint32_t R;
            struct {
                vuint32_t FILTER1_CRC:16;
                vuint32_t FILTER0_CRC:16;
            } B;
        } RWK_FILTER01_CRC;
        union {
            vuint32_t R;
            struct {
                vuint32_t FILTER3_CRC:16;
                vuint32_t FILTER2_CRC:16;
            } B;
        } RWK_FILTER23_CRC;
    };

    vuint8_t ADR_reserved33[8];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_3:10;
            vuint32_t LPITCSE:1;
            vuint32_t LPIATE:1;
            vuint32_t LPITXA:1;
            vuint32_t PLSEN:1;
            vuint32_t PLS:1;
            vuint32_t LPIEN:1;
            vuint32_t unused_1:6;
            vuint32_t RLPIST:1;
            vuint32_t TLPIST:1;
            vuint32_t unused_0:4;
            vuint32_t RLPIEX:1;
            vuint32_t RLPIEN:1;
            vuint32_t TLPIEX:1;
            vuint32_t TLPIEN:1;
        } B;
    } MAC_LPI_CONTROL_STATUS;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:6;
            vuint32_t LST:10;
            vuint32_t TWT:16;
        } B;
    } MAC_LPI_TIMERS_CONTROL;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:12;
            vuint32_t LPIET:17;
            vuint32_t unused_0:3;
        } B;
    } MAC_LPI_ENTRY_TIMER;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:20;
            vuint32_t TIC_1US_CNTR:12;
        } B;
    } MAC_1US_TIC_COUNTER;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_4:13;
            vuint32_t SGMRAL:1;
            vuint32_t LR:1;
            vuint32_t ECD:1;
            vuint32_t unused_3:1;
            vuint32_t ELE:1;
            vuint32_t unused_2:1;
            vuint32_t ANE:1;
            vuint32_t unused_1:2;
            vuint32_t RAN:1;
            vuint32_t unused_0:9;
        } B;
    } MAC_AN_CONTROL;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_4:23;
            vuint32_t ES:1;
            vuint32_t unused_3:2;
            vuint32_t ANC:1;
            vuint32_t unused_2:1;
            vuint32_t ANS:1;
            vuint32_t LS:1;
            vuint32_t unused_0:2;
        } B;
    } MAC_AN_STATUS;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_3:16;
            vuint32_t NP:1;
            vuint32_t unused_2:1;
            vuint32_t RFE:2;
            vuint32_t unused_1:3;
            vuint32_t PSE:2;
            vuint32_t HD:1;
            vuint32_t FD:1;
            vuint32_t unused_0:5;
        } B;
    } MAC_AN_ADVERTISEMENT;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_2:16;
            vuint32_t NP:1;
            vuint32_t ACK:1;
            vuint32_t RFE:2;
            vuint32_t unused_1:3;
            vuint32_t PSE:2;
            vuint32_t HD:1;
            vuint32_t FD:1;
            vuint32_t unused_0:5;
        } B;
    } MAC_AN_LINK_PARTNER_ABILITY;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:29;
            vuint32_t NPA:1;
            vuint32_t NPR:1;
            vuint32_t unused_0:1;
        } B;
    } MAC_AN_EXPANSION;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:16;
            vuint32_t GFD:1;
            vuint32_t GHD:1;
            vuint32_t unused_0:14;
        } B;
    } MAC_TBI_EXTENDED_STATUS;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_2:10;
            vuint32_t FALSCARDET:1;
            vuint32_t JABTO:1;
            vuint32_t LNKSTS:1;
            vuint32_t LNKSPEED:1;
            vuint32_t LNKMOD:1;
            vuint32_t unused_1:11;
            vuint32_t SMIDRXS:2;
            vuint32_t unused_0:1;
            vuint32_t SFTERR:1;
            vuint32_t LUD:1;
            vuint32_t TC:1;
        } B;
    } MAC_PHYIF_CONTROL_STATUS;

    vuint8_t ADR_reserved34[20];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:16;
            vuint32_t USERVER:8;
            vuint32_t SNPSVER:8;
        } B;
    } MAC_VERSION;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:13;
            vuint32_t TFCSTS:2;
            vuint32_t TPESTS:1;
            vuint32_t unused_0:13;
            vuint32_t RFCFCSTS:2;
            vuint32_t RPESTS:1;
        } B;
    } MAC_DEBUG;

    vuint8_t ADR_reserved35[4];

    union {
        vuint32_t R;
        struct {
            vuint32_t ACTPHYSEL:4;
            vuint32_t SAVLANINS:1;
            vuint32_t TSSTSSEL:2;
            vuint32_t MACADR64SEL:1;
            vuint32_t MACADR32SEL:1;
            vuint32_t ADDMACADRSEL:5;
            vuint32_t unused_4:1;
            vuint32_t RXCOESEL:1;
            vuint32_t unused_3:1;
            vuint32_t TXCOESEL:1;
            vuint32_t EEESEL:1;
            vuint32_t TSSEL:1;
            vuint32_t unused_2:2;
            vuint32_t ARPOFFSEL:1;
            vuint32_t MMCSEL:1;
            vuint32_t MGKSEL:1;
            vuint32_t RWKSEL:1;
            vuint32_t SMASEL:1;
            vuint32_t VLHASH:1;
            vuint32_t PCSSEL:1;
            vuint32_t HDSEL:1;
            vuint32_t GMIISEL:1;
            vuint32_t MIISEL:1;
        } B;
    } MAC_HW_FEATURE0;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_4:1;
            vuint32_t L3L4FNUM:4;
            vuint32_t unused_3:1;
            vuint32_t HASHTBLSZ:2;
            vuint32_t POUOST:1;
            vuint32_t unused_2:1;
            vuint32_t RAVSEL:1;
            vuint32_t AVSEL:1;
            vuint32_t DBGMEMA:1;
            vuint32_t TSOEN:1;
            vuint32_t SPHEN:1;
            vuint32_t DCBEN:1;
            vuint32_t ADDR64:2;
            vuint32_t ADVTHWORD:1;
            vuint32_t PTOEN:1;
            vuint32_t OSTEN:1;
            vuint32_t TXFIFOSIZE:5;
            vuint32_t SPRAM:1;
            vuint32_t RXFIFOSIZE:5;
        } B;
    } MAC_HW_FEATURE1;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_5:1;
            vuint32_t AUXSNAPNUM:3;
            vuint32_t unused_4:1;
            vuint32_t PPSOUTNUM:3;
            vuint32_t TDCSZ:2;
            vuint32_t TXCHCNT:4;
            vuint32_t RDCSZ:2;
            vuint32_t RXCHCNT:4;
            vuint32_t unused_1:2;
            vuint32_t TXQCNT:4;
            vuint32_t unused_0:2;
            vuint32_t RXQCNT:4;
        } B;
    } MAC_HW_FEATURE2;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_4:2;
            vuint32_t ASP:2;
            vuint32_t TBSSEL:1;
            vuint32_t FPESEL:1;
            vuint32_t unused_3:4;
            vuint32_t ESTWID:2;
            vuint32_t ESTDEP:3;
            vuint32_t ESTSEL:1;
            vuint32_t unused_2:1;
            vuint32_t FRPES:2;
            vuint32_t FRPBS:2;
            vuint32_t FRPSEL:1;
            vuint32_t PDUPSEL:1;
            vuint32_t unused_1:3;
            vuint32_t DVLAN:1;
            vuint32_t CBTISEL:1;
            vuint32_t unused_0:1;
            vuint32_t NRVF:3;
        } B;
    } MAC_HW_FEATURE3;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:30;
            vuint32_t PCSEL:2;
        } B;
    } MAC_HW_FEATURE4;

    vuint8_t ADR_reserved36[16];

    union {
		vuint32_t R;
		struct {
			vuint32_t unused_1:3;
			vuint32_t DCPES:1;
			vuint32_t MRWCPES:1;
			vuint32_t MTFCPES:1;
			vuint32_t MTBUPES:1;
			vuint32_t FSMPES:1;
			vuint32_t unused_0:6;
			vuint32_t SLVTES:1;
			vuint32_t MSTTES:1;
			vuint32_t RVCTES:1;
			vuint32_t R125ES:1;
			vuint32_t T125ES:1;
			vuint32_t PTES:1;
			vuint32_t ATES:1;
			vuint32_t CTES:1;
			vuint32_t RTES:1;
			vuint32_t TTES:1;
			vuint32_t ASRPES:1;
			vuint32_t CWPES:1;
			vuint32_t ARPES:1;
			vuint32_t MTSPES:1;
			vuint32_t MPES:1;
			vuint32_t RDPES:1;
			vuint32_t TPES:1;
			vuint32_t ATPES:1;
		} B;
	} MAC_DPP_FSM_INTERRUPT_STATUS;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:18;
            vuint32_t ASPEAS:14;
        } B;
    } MAC_AXI_SLV_DPE_ADDR_STATUS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RVCLGRNML:1;
            vuint32_t R125LGRNML:1;
            vuint32_t T125LGRNML:1;
            vuint32_t PLGRNML:1;
            vuint32_t ALGRNML:1;
            vuint32_t CLGRNML:1;
            vuint32_t RLGRNML:1;
            vuint32_t TLGRNML:1;
            vuint32_t RVCPEIN:1;
            vuint32_t R125PEIN:1;
            vuint32_t T125PEIN:1;
            vuint32_t PPEIN:1;
            vuint32_t APEIN:1;
            vuint32_t CPEIN:1;
            vuint32_t RPEIN:1;
            vuint32_t TPEIN:1;
            vuint32_t RVCTEIN:1;
            vuint32_t R125TEIN:1;
            vuint32_t T125TEIN:1;
            vuint32_t PTEIN:1;
            vuint32_t ATEIN:1;
            vuint32_t CTEIN:1;
            vuint32_t RTEIN:1;
            vuint32_t TTEIN:1;
            vuint32_t unused_0:6;
            vuint32_t PRTYEN:1;
            vuint32_t TMOUTEN:1;
        } B;
    } MAC_FSM_CONTROL;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:8;
            vuint32_t LTMRMD:4;
            vuint32_t NTMRMD:4;
            vuint32_t unused_0:6;
            vuint32_t TMR:10;
        } B;
    } MAC_FSM_ACT_TIMER;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:16;
            vuint32_t MAC_SCS1:16;
        } B;
    } SNPS_SCS_REG1;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:12;
            vuint32_t B10T1SFSPES:1;
            vuint32_t XTFTES:1;
            vuint32_t R2_5FTES:1;
            vuint32_t T2_5FTES:1;
            vuint32_t unused_0:15;
            vuint32_t PVDLPES:1;
        } B;
    } MAC_10BT1S_DPP_FSM_INPUT_STATUS;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:7;
            vuint32_t XTLNMS:1;
            vuint32_t R2P5LNMS:1;
            vuint32_t T2P5LNMS:1;
            vuint32_t XTFTEI:1;
            vuint32_t R2P5FTEI:1;
            vuint32_t T2P5FTEI:1;
            vuint32_t XTFPEI:1;
            vuint32_t R2P5FPEI:1;
            vuint32_t T2P5FPEI:1;
            vuint32_t unused_0:15;
            vuint32_t IPEPVDL:1;
        } B;
    } MAC_10BT1S_DPP_FSM_CONTROL;

    vuint8_t ADR_reserved37[164];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_2:3;
            vuint32_t RAT:1;
            vuint32_t PSE:1;
            vuint32_t BTB:1;
            vuint32_t PA:5;
            vuint32_t RDA:5;
            vuint32_t unused_1:1;
            vuint32_t NTC:3;
            vuint32_t CR:4;
            vuint32_t unused_0:3;
            vuint32_t SKAP:1;
            vuint32_t GOC:2;
            vuint32_t C45E:1;
            vuint32_t GB:1;
        } B;
    } MAC_MDIO_ADDRESS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RA:16;
            vuint32_t GD:16;
        } B;
    } MAC_MDIO_DATA;

    union {
        vuint32_t R;
        struct {
            vuint32_t GPIT:16;
            vuint32_t unused_0:12;
            vuint32_t GPIE:4;
        } B;
    } MAC_GPIO_CONTROL;

    union {
        vuint32_t R;
        struct {
            vuint32_t GPO:16;
            vuint32_t GPIS:16;
        } B;
    } MAC_GPIO_STATUS;

    union {
        vuint32_t R;
        struct {
            vuint32_t ARPPA:32;
        } B;
    } MAC_ARP_ADDRESS;

    vuint8_t ADR_reserved38[28];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:31;
            vuint32_t RCWE:1;
        } B;
    } MAC_CSR_SW_CTRL;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:12;
            vuint32_t TRSP:1;
            vuint32_t TVER:1;
            vuint32_t RRSP:1;
            vuint32_t RVER:1;
            vuint32_t unused_0:11;
            vuint32_t S1_SET_0:1;
            vuint32_t ARV:1;
            vuint32_t SRSP:1;
            vuint32_t SVER:1;
            vuint32_t EFPE:1;
        } B;
    } MAC_FPE_CTRL_STS;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_3:6;
            vuint32_t SAVE:1;
            vuint32_t unused_2:1;
            vuint32_t SAVO:7;
            vuint32_t unused_1:6;
            vuint32_t SPLM:2;
            vuint32_t unused_0:1;
            vuint32_t SPLOFST:7;
        } B;
    } MAC_EXT_CFG1;

    vuint8_t ADR_reserved39[4];

    union {
        vuint32_t R;
        struct {
            vuint32_t MPTN:32;
        } B;
    } MAC_PRESN_TIME_NS;

    union {
        vuint32_t R;
        struct {
            vuint32_t MPTU:32;
        } B;
    } MAC_PRESN_TIME_UPDT;    

    vuint8_t ADR_reserved40[184];

    union {
        vuint32_t R;
        struct {
            vuint32_t AE:1;
            vuint32_t unused_0:13;
            vuint32_t DCS:2;
            vuint32_t ADDRHI:16;
        } B;
    } MAC_ADDRESS0_HIGH;

    union {
        vuint32_t R;
        struct {
            vuint32_t ADDRLO:32;
        } B;
    } MAC_ADDRESS0_LOW;

    struct {
        union {
            vuint32_t R;
            struct {
                vuint32_t AE:1;
                vuint32_t SA:1;
                vuint32_t MBC:6;
                vuint32_t unused_0:6;
                vuint32_t DCS:2;
                vuint32_t ADDRHI:16;
            } B;
        } MAC_ADDRESS_HIGH;

        union {
            vuint32_t R;
            struct {
                vuint32_t ADDRLO:32;
            } B;
        } MAC_ADDRESS_LOW;

    } MAC_PF_1_31[31];

    vuint8_t ADR_reserved41[768];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:23;
            vuint32_t UCDBC:1;
            vuint32_t unused_0:2;
            vuint32_t CNTPRSTLVL:1;
            vuint32_t CNTPRST:1;
            vuint32_t CNTFREEZ:1;
            vuint32_t RSTONRD:1;
            vuint32_t CNTSTOPRO:1;
            vuint32_t CNTRST:1;
        } B;
    } MMC_CONTROL;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:4;
            vuint32_t RXLPITRCIS:1;
            vuint32_t RXLPIUSCIS:1;
            vuint32_t RXCTRLPIS:1;
            vuint32_t RXRCVERRPIS:1;
            vuint32_t RXWDOGPIS:1;
            vuint32_t RXVLANGBPIS:1;
            vuint32_t RXFOVPIS:1;
            vuint32_t RXPAUSPIS:1;
            vuint32_t RXORANGEPIS:1;
            vuint32_t RXLENERPIS:1;
            vuint32_t RXUCGPIS:1;
            vuint32_t RX1024TMAXOCTGBPIS:1;
            vuint32_t RX512T1023OCTGBPIS:1;
            vuint32_t RX256T511OCTGBPIS:1;
            vuint32_t RX128T255OCTGBPIS:1;
            vuint32_t RX65T127OCTGBPIS:1;
            vuint32_t RX64OCTGBPIS:1;
            vuint32_t RXOSIZEGPIS:1;
            vuint32_t RXUSIZEGPIS:1;
            vuint32_t RXJABERPIS:1;
            vuint32_t RXRUNTPIS:1;
            vuint32_t RXALGNERPIS:1;
            vuint32_t RXCRCERPIS:1;
            vuint32_t RXMCGPIS:1;
            vuint32_t RXBCGPIS:1;
            vuint32_t RXGOCTIS:1;
            vuint32_t RXGBOCTIS:1;
            vuint32_t RXGBPKTIS:1;
        } B;
    } MMC_RX_INTERRUPT;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:4;
            vuint32_t TXLPITRCIS:1;
            vuint32_t TXLPIUSCIS:1;
            vuint32_t TXOSIZEGPIS:1;
            vuint32_t TXVLANGPIS:1;
            vuint32_t TXPAUSPIS:1;
            vuint32_t TXEXDEFPIS:1;
            vuint32_t TXGPKTIS:1;
            vuint32_t TXGOCTIS:1;
            vuint32_t TXCARERPIS:1;
            vuint32_t TXEXCOLPIS:1;
            vuint32_t TXLATCOLPIS:1;
            vuint32_t TXDEFPIS:1;
            vuint32_t TXMCOLGPIS:1;
            vuint32_t TXSCOLGPIS:1;
            vuint32_t TXUFLOWERPIS:1;
            vuint32_t TXBCGBPIS:1;
            vuint32_t TXMCGBPIS:1;
            vuint32_t TXUCGBPIS:1;
            vuint32_t TX1024TMAXOCTGBPIS:1;
            vuint32_t TX512T1023OCTGBPIS:1;
            vuint32_t TX256T511OCTGBPIS:1;
            vuint32_t TX128T255OCTGBPIS:1;
            vuint32_t TX65T127OCTGBPIS:1;
            vuint32_t TX64OCTGBPIS:1;
            vuint32_t TXMCGPIS:1;
            vuint32_t TXBCGPIS:1;
            vuint32_t TXGBPKTIS:1;
            vuint32_t TXGBOCTIS:1;
        } B;
    } MMC_TX_INTERRUPT;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:4;
            vuint32_t RXLPITRCIM:1;
            vuint32_t RXLPIUSCIM:1;
            vuint32_t RXCTRLPIM:1;
            vuint32_t RXRCVERRPIM:1;
            vuint32_t RXWDOGPIM:1;
            vuint32_t RXVLANGBPIM:1;
            vuint32_t RXFOVPIM:1;
            vuint32_t RXPAUSPIM:1;
            vuint32_t RXORANGEPIM:1;
            vuint32_t RXLENERPIM:1;
            vuint32_t RXUCGPIM:1;
            vuint32_t RX1024TMAXOCTGBPIM:1;
            vuint32_t RX512T1023OCTGBPIM:1;
            vuint32_t RX256T511OCTGBPIM:1;
            vuint32_t RX128T255OCTGBPIM:1;
            vuint32_t RX65T127OCTGBPIM:1;
            vuint32_t RX64OCTGBPIM:1;
            vuint32_t RXOSIZEGPIM:1;
            vuint32_t RXUSIZEGPIM:1;
            vuint32_t RXJABERPIM:1;
            vuint32_t RXRUNTPIM:1;
            vuint32_t RXALGNERPIM:1;
            vuint32_t RXCRCERPIM:1;
            vuint32_t RXMCGPIM:1;
            vuint32_t RXBCGPIM:1;
            vuint32_t RXGOCTIM:1;
            vuint32_t RXGBOCTIM:1;
            vuint32_t RXGBPKTIM:1;
        } B;
    } MMC_RX_INTERRUPT_MASK;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:4;
            vuint32_t TXLPITRCIM:1;
            vuint32_t TXLPIUSCIM:1;
            vuint32_t TXOSIZEGPIM:1;
            vuint32_t TXVLANGPIM:1;
            vuint32_t TXPAUSPIM:1;
            vuint32_t TXEXDEFPIM:1;
            vuint32_t TXGPKTIM:1;
            vuint32_t TXGOCTIM:1;
            vuint32_t TXCARERPIM:1;
            vuint32_t TXEXCOLPIM:1;
            vuint32_t TXLATCOLPIM:1;
            vuint32_t TXDEFPIM:1;
            vuint32_t TXMCOLGPIM:1;
            vuint32_t TXSCOLGPIM:1;
            vuint32_t TXUFLOWERPIM:1;
            vuint32_t TXBCGBPIM:1;
            vuint32_t TXMCGBPIM:1;
            vuint32_t TXUCGBPIM:1;
            vuint32_t TX1024TMAXOCTGBPIM:1;
            vuint32_t TX512T1023OCTGBPIM:1;
            vuint32_t TX256T511OCTGBPIM:1;
            vuint32_t TX128T255OCTGBPIM:1;
            vuint32_t TX65T127OCTGBPIM:1;
            vuint32_t TX64OCTGBPIM:1;
            vuint32_t TXMCGPIM:1;
            vuint32_t TXBCGPIM:1;
            vuint32_t TXGBPKTIM:1;
            vuint32_t TXGBOCTIM:1;
        } B;
    } MMC_TX_INTERRUPT_MASK;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXOCTGB:32;
        } B;
    } TX_OCTET_COUNT_GOOD_BAD;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXPKTGB:32;
        } B;
    } TX_PACKET_COUNT_GOOD_BAD;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXBCASTG:32;
        } B;
    } TX_BROADCAST_PACKETS_GOOD;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXMCASTG:32;
        } B;
    } TX_MULTICAST_PACKETS_GOOD;

    union {
        vuint32_t R;
        struct {
            vuint32_t TX64OCTGB:32;
        } B;
    } TX_64OCTETS_PACKETS_GOOD_BAD;

    union {
        vuint32_t R;
        struct {
            vuint32_t TX65_127OCTGB:32;
        } B;
    } TX_65TO127OCTETS_PACKETS_GOOD_BAD;

    union {
        vuint32_t R;
        struct {
            vuint32_t TX128_255OCTGB:32;
        } B;
    } TX_128TO255OCTETS_PACKETS_GOOD_BAD;

    union {
        vuint32_t R;
        struct {
            vuint32_t TX256_511OCTGB:32;
        } B;
    } TX_256TO511OCTETS_PACKETS_GOOD_BAD;

    union {
        vuint32_t R;
        struct {
            vuint32_t TX512_1023OCTGB:32;
        } B;
    } TX_512TO1023OCTETS_PACKETS_GOOD_BAD;

    union {
        vuint32_t R;
        struct {
            vuint32_t TX1024_MAXOCTGB:32;
        } B;
    } TX_1024TOMAXOCTETS_PACKETS_GOOD_BAD;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXUCASTGB:32;
        } B;
    } TX_UNICAST_PACKETS_GOOD_BAD;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXMCASTGB:32;
        } B;
    } TX_MULTICAST_PACKETS_GOOD_BAD;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXBCASTGB:32;
        } B;
    } TX_BROADCAST_PACKETS_GOOD_BAD;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXUNDRFLW:32;
        } B;
    } TX_UNDERFLOW_ERROR_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXSNGLCOLG:32;
        } B;
    } TX_SINGLE_COLLISION_GOOD_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXMULTLCOLG:32;
        } B;
    } TX_MULTIPLE_COLLISION_GOOD_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXDEFRD:32;
        } B;
    } TX_DEFERRED_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXLATECOL:32;
        } B;
    } TX_LATE_COLLISION_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXEXSCOL:32;
        } B;
    } TX_EXCESSIVE_COLLISION_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXCARR:32;
        } B;
    } TX_CARRIER_ERROR_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXOCTG:32;
        } B;
    } TX_OCTET_COUNT_GOOD;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXPKTG:32;
        } B;
    } TX_PACKET_COUNT_GOOD;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXEXSDEF:32;
        } B;
    } TX_EXCESSIVE_DEFERRAL_ERROR;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXPAUSE:32;
        } B;
    } TX_PAUSE_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXVLANG:32;
        } B;
    } TX_VLAN_PACKETS_GOOD;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXOSIZG:32;
        } B;
    } TX_OSIZE_PACKETS_GOOD;

    vuint8_t ADR_reserved42[4];

    union {
        vuint32_t R;
        struct {
            vuint32_t RXPKTGB:32;
        } B;
    } RX_PACKETS_COUNT_GOOD_BAD;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXOCTGB:32;
        } B;
    } RX_OCTET_COUNT_GOOD_BAD;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXOCTG:32;
        } B;
    } RX_OCTET_COUNT_GOOD;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXBCASTG:32;
        } B;
    } RX_BROADCAST_PACKETS_GOOD;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXMCASTG:32;
        } B;
    } RX_MULTICAST_PACKETS_GOOD;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXCRCERR:32;
        } B;
    } RX_CRC_ERROR_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXALGNERR:32;
        } B;
    } RX_ALIGNMENT_ERROR_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXRUNTERR:32;
        } B;
    } RX_RUNT_ERROR_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXJABERR:32;
        } B;
    } RX_JABBER_ERROR_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXUNDERSZG:32;
        } B;
    } RX_UNDERSIZE_PACKETS_GOOD;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXOVERSZG:32;
        } B;
    } RX_OVERSIZE_PACKETS_GOOD;

    union {
        vuint32_t R;
        struct {
            vuint32_t RX64OCTGB:32;
        } B;
    } RX_64OCTETS_PACKETS_GOOD_BAD;

    union {
        vuint32_t R;
        struct {
            vuint32_t RX65_127OCTGB:32;
        } B;
    } RX_65TO127OCTETS_PACKETS_GOOD_BAD;

    union {
        vuint32_t R;
        struct {
            vuint32_t RX128_255OCTGB:32;
        } B;
    } RX_128TO255OCTETS_PACKETS_GOOD_BAD;

    union {
        vuint32_t R;
        struct {
            vuint32_t RX256_511OCTGB:32;
        } B;
    } RX_256TO511OCTETS_PACKETS_GOOD_BAD;

    union {
        vuint32_t R;
        struct {
            vuint32_t RX512_1023OCTGB:32;
        } B;
    } RX_512TO1023OCTETS_PACKETS_GOOD_BAD;

    union {
        vuint32_t R;
        struct {
            vuint32_t RX1024_MAXOCTGB:32;
        } B;
    } RX_1024TOMAXOCTETS_PACKETS_GOOD_BAD;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXUCASTG:32;
        } B;
    } RX_UNICAST_PACKETS_GOOD;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXLENERR:32;
        } B;
    } RX_LENGTH_ERROR_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXOUTOFRNG:32;
        } B;
    } RX_OUT_OF_RANGE_TYPE_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXPAUSEPKT:32;
        } B;
    } RX_PAUSE_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXFIFOOVFL:32;
        } B;
    } RX_FIFO_OVERFLOW_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXVLANPKTGB:32;
        } B;
    } RX_VLAN_PACKETS_GOOD_BAD;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXWDGERR:32;
        } B;
    } RX_WATCHDOG_ERROR_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXRCVERR:32;
        } B;
    } RX_RECEIVE_ERROR_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXCTRLG:32;
        } B;
    } RX_CONTROL_PACKETS_GOOD;

    vuint8_t ADR_reserved43[4];

    union {
        vuint32_t R;
        struct {
            vuint32_t TXLPIUSC:32;
        } B;
    } TX_LPI_USEC_CNTR;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXLPITRC:32;
        } B;
    } TX_LPI_TRAN_CNTR;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXLPIUSC:32;
        } B;
    } RX_LPI_USEC_CNTR;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXLPITRC:32;
        } B;
    } RX_LPI_TRAN_CNTR;

    vuint8_t ADR_reserved44[4];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:2;
            vuint32_t RXICMPEROIM:1;
            vuint32_t RXICMPGOIM:1;
            vuint32_t RXTCPEROIM:1;
            vuint32_t RXTCPGOIM:1;
            vuint32_t RXUDPEROIM:1;
            vuint32_t RXUDPGOIM:1;
            vuint32_t RXIPV6NOPAYOIM:1;
            vuint32_t RXIPV6HEROIM:1;
            vuint32_t RXIPV6GOIM:1;
            vuint32_t RXIPV4UDSBLOIM:1;
            vuint32_t RXIPV4FRAGOIM:1;
            vuint32_t RXIPV4NOPAYOIM:1;
            vuint32_t RXIPV4HEROIM:1;
            vuint32_t RXIPV4GOIM:1;
            vuint32_t unused_0:2;
            vuint32_t RXICMPERPIM:1;
            vuint32_t RXICMPGPIM:1;
            vuint32_t RXTCPERPIM:1;
            vuint32_t RXTCPGPIM:1;
            vuint32_t RXUDPERPIM:1;
            vuint32_t RXUDPGPIM:1;
            vuint32_t RXIPV6NOPAYPIM:1;
            vuint32_t RXIPV6HERPIM:1;
            vuint32_t RXIPV6GPIM:1;
            vuint32_t RXIPV4UDSBLPIM:1;
            vuint32_t RXIPV4FRAGPIM:1;
            vuint32_t RXIPV4NOPAYPIM:1;
            vuint32_t RXIPV4HERPIM:1;
            vuint32_t RXIPV4GPIM:1;
        } B;
    } MMC_IPC_RX_INTERRUPT_MASK;

    vuint8_t ADR_reserved45[4];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:2;
            vuint32_t RXICMPEROIS:1;
            vuint32_t RXICMPGOIS:1;
            vuint32_t RXTCPEROIS:1;
            vuint32_t RXTCPGOIS:1;
            vuint32_t RXUDPEROIS:1;
            vuint32_t RXUDPGOIS:1;
            vuint32_t RXIPV6NOPAYOIS:1;
            vuint32_t RXIPV6HEROIS:1;
            vuint32_t RXIPV6GOIS:1;
            vuint32_t RXIPV4UDSBLOIS:1;
            vuint32_t RXIPV4FRAGOIS:1;
            vuint32_t RXIPV4NOPAYOIS:1;
            vuint32_t RXIPV4HEROIS:1;
            vuint32_t RXIPV4GOIS:1;
            vuint32_t unused_0:2;
            vuint32_t RXICMPERPIS:1;
            vuint32_t RXICMPGPIS:1;
            vuint32_t RXTCPERPIS:1;
            vuint32_t RXTCPGPIS:1;
            vuint32_t RXUDPERPIS:1;
            vuint32_t RXUDPGPIS:1;
            vuint32_t RXIPV6NOPAYPIS:1;
            vuint32_t RXIPV6HERPIS:1;
            vuint32_t RXIPV6GPIS:1;
            vuint32_t RXIPV4UDSBLPIS:1;
            vuint32_t RXIPV4FRAGPIS:1;
            vuint32_t RXIPV4NOPAYPIS:1;
            vuint32_t RXIPV4HERPIS:1;
            vuint32_t RXIPV4GPIS:1;
        } B;
    } MMC_IPC_RX_INTERRUPT;

    vuint8_t ADR_reserved46[4];

    union {
        vuint32_t R;
        struct {
            vuint32_t RXIPV4GDPKT:32;
        } B;
    } RXIPV4_GOOD_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXIPV4HDRERRPKT:32;
        } B;
    } RXIPV4_HEADER_ERROR_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXIPV4NOPAYPKT:32;
        } B;
    } RXIPV4_NO_PAYLOAD_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXIPV4FRAGPKT:32;
        } B;
    } RXIPV4_FRAGMENTED_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXIPV4UDSBLPKT:32;
        } B;
    } RXIPV4_UDP_CHECKSUM_DISABLED_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXIPV6GDPKT:32;
        } B;
    } RXIPV6_GOOD_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXIPV6HDRERRPKT:32;
        } B;
    } RXIPV6_HEADER_ERROR_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXIPV6NOPAYPKT:32;
        } B;
    } RXIPV6_NO_PAYLOAD_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXUDPGDPKT:32;
        } B;
    } RXUDP_GOOD_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXUDPERRPKT:32;
        } B;
    } RXUDP_ERROR_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXTCPGDPKT:32;
        } B;
    } RXTCP_GOOD_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXTCPERRPKT:32;
        } B;
    } RXTCP_ERROR_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXICMPGDPKT:32;
        } B;
    } RXICMP_GOOD_PACKETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXICMPERRPKT:32;
        } B;
    } RXICMP_ERROR_PACKETS;

    vuint8_t ADR_reserved47[8];

    union {
        vuint32_t R;
        struct {
            vuint32_t RXIPV4GDOCT:32;
        } B;
    } RXIPV4_GOOD_OCTETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXIPV4HDRERROCT:32;
        } B;
    } RXIPV4_HEADER_ERROR_OCTETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXIPV4NOPAYOCT:32;
        } B;
    } RXIPV4_NO_PAYLOAD_OCTETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXIPV4FRAGOCT:32;
        } B;
    } RXIPV4_FRAGMENTED_OCTETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXIPV4UDSBLOCT:32;
        } B;
    } RXIPV4_UDP_CHECKSUM_DISABLE_OCTETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXIPV6GDOCT:32;
        } B;
    } RXIPV6_GOOD_OCTETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXIPV6HDRERROCT:32;
        } B;
    } RXIPV6_HEADER_ERROR_OCTETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXIPV6NOPAYOCT:32;
        } B;
    } RXIPV6_NO_PAYLOAD_OCTETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXUDPGDOCT:32;
        } B;
    } RXUDP_GOOD_OCTETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXUDPERROCT:32;
        } B;
    } RXUDP_ERROR_OCTETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXTCPGDOCT:32;
        } B;
    } RXTCP_GOOD_OCTETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXTCPERROCT:32;
        } B;
    } RXTCP_ERROR_OCTETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXICMPGDOCT:32;
        } B;
    } RXICMP_GOOD_OCTETS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXICMPERROCT:32;
        } B;
    } RXICMP_ERROR_OCTETS;

    vuint8_t ADR_reserved48[24];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:30;
            vuint32_t HRCIS:1;
            vuint32_t FCIS:1;
        } B;
    } MMC_FPE_TX_INTERRUPT;    

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:30;
            vuint32_t HRCIM:1;
            vuint32_t FCIM:1;
        } B;
    } MMC_FPE_TX_INTERRUPT_MASK;  

    union {
        vuint32_t R;
        struct {
            vuint32_t TXFFC:32;
        } B;
    } MMC_TX_FPE_FRAGMENT_CNTR;  

    union {
        vuint32_t R;
        struct {
            vuint32_t TXHRC:32;
        } B;
    } MMC_TX_HOLD_REQ_CNTR;  

    vuint8_t ADR_reserved49[16];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:28;
            vuint32_t FCIS:1;
            vuint32_t PAOCIS:1;
            vuint32_t PSECIS:1;
            vuint32_t PAECIS:1;
        } B;
    } MMC_FPE_RX_INTERRUPT;  

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:28;
            vuint32_t FCIM:1;
            vuint32_t PAOCIM:1;
            vuint32_t PSECIM:1;
            vuint32_t PAECIM:1;
        } B;
    } MMC_FPE_RX_INTERRUPT_MASK;  

    union {
        vuint32_t R;
        struct {
            vuint32_t PAEC:32;
        } B;
    } MMC_RX_PACKET_ASSEMBLY_ERR_CNTR;  

    union {
        vuint32_t R;
        struct {
            vuint32_t PSEC:32;
        } B;
    } MMC_RX_PACKET_SMD_ERR_CNTR;  

    union {
        vuint32_t R;
        struct {
            vuint32_t PAOC:32;
        } B;
    } MMC_RX_PACKET_ASSEMBLY_OK_CNTR;  

    union {
        vuint32_t R;
        struct {
            vuint32_t FFC:32;
        } B;
    } MMC_RX_FPE_FRAGMENT_CNTR;  

    vuint8_t ADR_reserved50[40];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_4:3;
            vuint32_t DMCHEN0:1;
            vuint32_t unused_3:3;
            vuint32_t DMCHN0:1;
            vuint32_t unused_2:2;
            vuint32_t L4DPIM0:1;
            vuint32_t L4DPM0:1;
            vuint32_t L4SPIM0:1;
            vuint32_t L4SPM0:1;
            vuint32_t unused_1:1;
            vuint32_t L4PEN0:1;
            vuint32_t L3HDBM0:5;
            vuint32_t L3HSBM0:5;
            vuint32_t L3DAIM0:1;
            vuint32_t L3DAM0:1;
            vuint32_t L3SAIM0:1;
            vuint32_t L3SAM0:1;
            vuint32_t unused_0:1;
            vuint32_t L3PEN0:1;
        } B;
    } MAC_L3_L4_CONTROL0;

    union {
        vuint32_t R;
        struct {
            vuint32_t L4DP0:16;
            vuint32_t L4SP0:16;
        } B;
    } MAC_LAYER4_ADDRESS0;

    vuint8_t ADR_reserved51[8];

    union {
        vuint32_t R;
        struct {
            vuint32_t L3A00:32;
        } B;
    } MAC_LAYER3_ADDR0_REG0;

    union {
        vuint32_t R;
        struct {
            vuint32_t L3A10:32;
        } B;
    } MAC_LAYER3_ADDR1_REG0;

    union {
        vuint32_t R;
        struct {
            vuint32_t L3A20:32;
        } B;
    } MAC_LAYER3_ADDR2_REG0;

    union {
        vuint32_t R;
        struct {
            vuint32_t L3A30:32;
        } B;
    } MAC_LAYER3_ADDR3_REG0;

    vuint8_t ADR_reserved52[336];

    union {
        vuint32_t R;
        struct {
            vuint32_t SNPS_R:1;
            vuint32_t unused_2:11;
            vuint32_t MSEL:4;
            vuint32_t AOFF:8;
            vuint32_t unused_1:2;
            vuint32_t AUTO:1;
            vuint32_t unused_0:3;
            vuint32_t COM:1;
            vuint32_t OB:1;
        } B;
    } MAC_INDIR_ACCESS_CTRL;

    union {
        vuint32_t R;
        struct {
            vuint32_t DATA:32;
        } B;
    } MAC_INDIR_ACCESS_DATA;

    union {
        vuint32_t R;
        struct {
            vuint32_t PCTIE:32;
        } B;
    } MAC_PCTH_INTR_ENABLE;

   union {
        vuint32_t R;
        struct {
            vuint32_t PCTIS:32;
        } B;
    } MAC_PCTH_INTR_STATUS;

    vuint8_t ADR_reserved53[32];

   union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:28;
            vuint32_t TWIE:4;
        } B;
    } MAC_PCTW_INTR_ENABLE;

   union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:28;
            vuint32_t TWIS:4;
        } B;
    } MAC_PCTW_INTR_STATUS;

    vuint8_t ADR_reserved54[88];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_4:3;
            vuint32_t AV8021ASMEN:1;
            vuint32_t unused_2:1;
            vuint32_t TITA:1;
            vuint32_t EPCSL:1;
            vuint32_t TXTSSTSM:1;
            vuint32_t unused_1:3;
            vuint32_t ESTI:1;
            vuint32_t CSC:1;
            vuint32_t TSENMACADDR:1;
            vuint32_t SNAPTYPSEL:2;
            vuint32_t TSMSTRENA:1;
            vuint32_t TSEVNTENA:1;
            vuint32_t TSIPV4ENA:1;
            vuint32_t TSIPV6ENA:1;
            vuint32_t TSIPENA:1;
            vuint32_t TSVER2ENA:1;
            vuint32_t TSCTRLSSR:1;
            vuint32_t TSENALL:1;
            vuint32_t unused_0:1;
            vuint32_t PTGE:1;
            vuint32_t TSADDREG:1;
            vuint32_t TSTRIG:1;
            vuint32_t TSUPDT:1;
            vuint32_t TSINIT:1;
            vuint32_t TSCFUPDT:1;
            vuint32_t TSENA:1;
        } B;
    } MAC_TIMESTAMP_CONTROL;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:8;
            vuint32_t SSINC:8;
            vuint32_t SNSINC:8;
            vuint32_t unused_0:8;
        } B;
    } MAC_SUB_SECOND_INCREMENT;

    union {
        vuint32_t R;
        struct {
            vuint32_t TSS:32;
        } B;
    } MAC_SYSTEM_TIME_SECONDS;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:1;
            vuint32_t TSSS:31;
        } B;
    } MAC_SYSTEM_TIME_NANOSECONDS;

    union {
        vuint32_t R;
        struct {
            vuint32_t TSS:32;
        } B;
    } MAC_SYSTEM_TIME_SECONDS_UPDATE;

    union {
        vuint32_t R;
        struct {
            vuint32_t ADDSUB:1;
            vuint32_t TSSS:31;
        } B;
    } MAC_SYSTEM_TIME_NANOSECONDS_UPDATE;

    union {
        vuint32_t R;
        struct {
            vuint32_t TSAR:32;
        } B;
    } MAC_TIMESTAMP_ADDEND;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:16;
            vuint32_t TSHWR:16;
        } B;
    } MAC_SYSTEM_TIME_HIGHER_WORD_SECONDS;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_2:2;
            vuint32_t ATSNS:5;
            vuint32_t ATSSTM:1;
            vuint32_t unused_1:4;
            vuint32_t ATSSTN:4;
            vuint32_t TXTSSIS:1;
            vuint32_t unused_0:5;
            vuint32_t TSTRGTERR3:1;
            vuint32_t TSTARGT3:1;
            vuint32_t TSTRGTERR2:1;
            vuint32_t TSTARGT2:1;
            vuint32_t TSTRGTERR1:1;
            vuint32_t TSTARGT1:1;
            vuint32_t TSTRGTERR0:1;
            vuint32_t AUXTSTRIG:1;
            vuint32_t TSTARGT0:1;
            vuint32_t TSSOVF:1;
        } B;
    } MAC_TIMESTAMP_STATUS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXNS:16;
            vuint32_t RXSNS:8;
            vuint32_t unused_0:8;
        } B;
    } MAC_RX_DOMAIN_TIME_INCR;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXNS:16;
            vuint32_t TXSNS:8;
            vuint32_t unused_0:8;
        } B;
    } MAC_TX_DOMAIN_TIME_INCR;

    vuint8_t ADR_reserved55[4];

    union {
        vuint32_t R;
        struct {
            vuint32_t TXTSSMIS:1;
            vuint32_t TXTSSLO:31;
        } B;
    } MAC_TX_TIMESTAMP_STATUS_NANOSECONDS;

    union {
        vuint32_t R;
        struct {
            vuint32_t TXTSSHI:32;
        } B;
    } MAC_TX_TIMESTAMP_STATUS_SECONDS;

    vuint8_t ADR_reserved56[8];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:24;
            vuint32_t ATSEN3:1;
            vuint32_t ATSEN2:1;
            vuint32_t ATSEN1:1;
            vuint32_t ATSEN0:1;
            vuint32_t unused_0:3;
            vuint32_t ATSFC:1;
        } B;
    } MAC_AUXILIARY_CONTROL;

    vuint8_t ADR_reserved57[4];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:1;
            vuint32_t AUXTSLO:31;
        } B;
    } MAC_AUXILIARY_TIMESTAMP_NANOSECONDS;

    union {
        vuint32_t R;
        struct {
            vuint32_t AUXTSHI:32;
        } B;
    } MAC_AUXILIARY_TIMESTAMP_SECONDS;

    union {
        vuint32_t R;
        struct {
            vuint32_t OSTIAC:32;
        } B;
    } MAC_TIMESTAMP_INGRESS_ASYM_CORR;

    union {
        vuint32_t R;
        struct {
            vuint32_t OSTEAC:32;
        } B;
    } MAC_TIMESTAMP_EGRESS_ASYM_CORR;

    union {
        vuint32_t R;
        struct {
            vuint32_t TSIC:32;
        } B;
    } MAC_TIMESTAMP_INGRESS_CORR_NANOSECOND;

    union {
        vuint32_t R;
        struct {
            vuint32_t TSEC:32;
        } B;
    } MAC_TIMESTAMP_EGRESS_CORR_NANOSECOND;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:16;
            vuint32_t TSICSNS:8;
            vuint32_t unused_0:8;
        } B;
    } MAC_TIMESTAMP_INGRESS_CORR_SUBNANOSEC;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:16;
            vuint32_t TSECSNS:8;
            vuint32_t unused_0:8;
        } B;
    } MAC_TIMESTAMP_EGRESS_CORR_SUBNANOSEC;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:4;
            vuint32_t ITLNS:12;
            vuint32_t ITLSNS:8;
            vuint32_t unused_0:8;
        } B;
    } MAC_TIMESTAMP_INGRESS_LATENCY;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:4;
            vuint32_t ETLNS:12;
            vuint32_t ETLSNS:8;
            vuint32_t unused_0:8;
        } B;
    } MAC_TIMESTAMP_ENGRESS_LATENCY;

    union {
        vuint32_t R;
        struct {
            vuint32_t MCGREN3:1;
            vuint32_t TRGTMODSEL3:2;
            vuint32_t TIMESEL:1;
            vuint32_t PPSCMD3:4;
            vuint32_t MCGREN2:1;
            vuint32_t TRGTMODSEL2:2;
            vuint32_t unused_1:1;
            vuint32_t PPSCMD2:4;
            vuint32_t MCGREN1:1;
            vuint32_t TRGTMODSEL1:2;
            vuint32_t unused_0:1;
            vuint32_t PPSCMD1:4;
            vuint32_t MCGREN0:1;
            vuint32_t TRGTMODSEL0:2;
            vuint32_t PPSEN0:1;
            vuint32_t PPSCTRL_PPSCMD:4;
        } B;
    } MAC_PPS_CONTROL;

    vuint8_t ADR_reserved58[12];

    union {
        vuint32_t R;
        struct {
            vuint32_t TSTRH0:32;
        } B;
    } MAC_PPS0_TARGET_TIME_SECONDS;

    union {
        vuint32_t R;
        struct {
            vuint32_t TRGTBUSY0:1;
            vuint32_t TTSL0:31;
        } B;
    } MAC_PPS0_TARGET_TIME_NANOSECONDS;

    union {
        vuint32_t R;
        struct {
            vuint32_t PPSINT0:32;
        } B;
    } MAC_PPS0_INTERVAL;

    union {
        vuint32_t R;
        struct {
            vuint32_t PPSWIDTH0:32;
        } B;
    } MAC_PPS0_WIDTH;

    vuint8_t ADR_reserved59[48];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:16;
            vuint32_t DN:8;
            vuint32_t PDRDIS:1;
            vuint32_t DRRDIS:1;
            vuint32_t APDREQTRIG:1;
            vuint32_t ASYNCTRIG:1;
            vuint32_t unused_0:1;
            vuint32_t APDREQEN:1;
            vuint32_t ASYNCEN:1;
            vuint32_t PTOEB:1;
        } B;
    } MAC_PTO_CONTROL;

    union {
        vuint32_t R;
        struct {
            vuint32_t SPI0:32;
        } B;
    } MAC_SOURCE_PORT_IDENTITY0;

    union {
        vuint32_t R;
        struct {
            vuint32_t SPI1:32;
        } B;
    } MAC_SOURCE_PORT_IDENTITY1;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:16;
            vuint32_t SPI2:16;
        } B;
    } MAC_SOURCE_PORT_IDENTITY2;

    union {
        vuint32_t R;
        struct {
            vuint32_t LMPDRI:8;
            vuint32_t unused_0:13;
            vuint32_t DRSYNCR:3;
            vuint32_t LSI:8;
        } B;
    } MAC_LOG_MESSAGE_INTERVAL;

    vuint8_t ADR_reserved60[44];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_4:16;
            vuint32_t FRPE:1;
            vuint32_t RXPED:1;
            vuint32_t unused_3:4;
            vuint32_t CNTCLR:1;
            vuint32_t CNTPRST:1;
            vuint32_t unused_2:1;
            vuint32_t SCHALG:2;
            vuint32_t unused_1:2;
            vuint32_t RAA:1;
            vuint32_t DTXSTS:1;
            vuint32_t unused_0:1;
        } B;
    } MTL_OPERATION_MODE;

    vuint8_t ADR_reserved61[4];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_2:13;
            vuint32_t EIEC:1;
            vuint32_t EIAEE:1;
            vuint32_t EIEE:1;
            vuint32_t STSIE:1;
            vuint32_t PKTIE:1;
            vuint32_t FIFOSEL:2;
            vuint32_t FIFOWREN:1;
            vuint32_t FIFORDEN:1;
            vuint32_t RSTSEL:1;
            vuint32_t RSTALL:1;
            vuint32_t unused_1:1;
            vuint32_t PKTSTATE:2;
            vuint32_t unused_0:1;
            vuint32_t BYTEEN:2;
            vuint32_t DBGMOD:1;
            vuint32_t FDBGEN:1;
        } B;
    } MTL_DBG_CTL;

    union {
        vuint32_t R;
        struct {
            vuint32_t LOCR:17;
            vuint32_t unused_1:5;
            vuint32_t STSI:1;
            vuint32_t PKTI:1;
            vuint32_t unused_0:3;
            vuint32_t BYTEEN:2;
            vuint32_t PKTSTATE:2;
            vuint32_t FIFOBUSY:1;
        } B;
    } MTL_DBG_STS;

    union {
        vuint32_t R;
        struct {
            vuint32_t FDBGDATA:32;
        } B;
    } MTL_FIFO_DEBUG_DATA;

    vuint8_t ADR_reserved62[12];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_2:8;
            vuint32_t MTLPIS:1;
            vuint32_t unused_1:4;
            vuint32_t ESTIS:1;
            vuint32_t DBGIS:1;
            vuint32_t MACIS:1;
            vuint32_t unused_0:8;
            vuint32_t Q7IS:1;
            vuint32_t Q6IS:1;
            vuint32_t Q5IS:1;
            vuint32_t Q4IS:1;
            vuint32_t Q3IS:1;
            vuint32_t Q2IS:1;
            vuint32_t Q1IS:1;
            vuint32_t Q0IS:1;
        } B;
    } MTL_INTERRUPT_STATUS;

    vuint8_t ADR_reserved63[12];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_7:3;
            vuint32_t Q3DDMACH:1;
            vuint32_t unused_6:1;
            vuint32_t Q3MDMACH:3;
            vuint32_t unused_5:3;
            vuint32_t Q2DDMACH:1;
            vuint32_t unused_4:1;
            vuint32_t Q2MDMACH:3;
            vuint32_t unused_3:3;
            vuint32_t Q1DDMACH:1;
            vuint32_t unused_2:1;
            vuint32_t Q1MDMACH:3;
            vuint32_t unused_1:3;
            vuint32_t Q0DDMACH:1;
            vuint32_t unused_0:1;
            vuint32_t Q0MDMACH:3;
        } B;
    } MTL_RXQ_DMA_MAP0;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_7:3;
            vuint32_t Q7DDMACH:1;
            vuint32_t unused_6:1;
            vuint32_t Q7MDMACH:3;
            vuint32_t unused_5:3;
            vuint32_t Q6DDMACH:1;
            vuint32_t unused_4:1;
            vuint32_t Q6MDMACH:3;
            vuint32_t unused_3:3;
            vuint32_t Q5DDMACH:1;
            vuint32_t unused_2:1;
            vuint32_t Q5MDMACH:3;
            vuint32_t unused_1:3;
            vuint32_t Q4DDMACH:1;
            vuint32_t unused_0:1;
            vuint32_t Q4MDMACH:3;
        } B;
    } MTL_RXQ_DMA_MAP1;

    vuint8_t ADR_reserved64[8];

    union {
        vuint32_t R;
        struct {
            vuint32_t LEOS:24;
            vuint32_t unused_1:1;
            vuint32_t LEGOS:3;
            vuint32_t unused_0:2;
            vuint32_t LEOV:1;
            vuint32_t ESTM:1;
        } B;
    } MTL_TBS_CTRL;

    vuint8_t ADR_reserved65[12];

    union {
        vuint32_t R;
        struct {
            vuint32_t PTOV:8;
            vuint32_t CTOV:12;
            vuint32_t unused_1:1;
            vuint32_t TILS:3;
            vuint32_t LCSE:2;
            vuint32_t DFBS:1;
            vuint32_t DDBF:1;
            vuint32_t QHLBF:1;
            vuint32_t unused_0:1;
            vuint32_t SSWL:1;
            vuint32_t EEST:1;
        } B;
    } MTL_EST_CONTROL;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:26;
            vuint32_t OVHD:6;
        } B;
    } MTL_EST_EXT_CONTROL;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:12;
            vuint32_t CGSN:4;
            vuint32_t BTRL:8;
            vuint32_t SWOL:1;
            vuint32_t unused_0:2;
            vuint32_t CGCE:1;
            vuint32_t HLBS:1;
            vuint32_t HLBF:1;
            vuint32_t BTRE:1;
            vuint32_t SWLC:1;
        } B;
    } MTL_EST_STATUS;

    vuint8_t ADR_reserved66[4];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:28;
            vuint32_t SEQN:4;
        } B;
    } MTL_EST_SCH_ERROR;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:28;
            vuint32_t FEQN:4;
        } B;
    } MTL_EST_FRM_SIZE_ERROR;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:14;
            vuint32_t HBFQ:2;
            vuint32_t unused_0:1;
            vuint32_t HBFS:15;
        } B;
    } MTL_EST_FRM_SIZE_CAPTURE;

    vuint8_t ADR_reserved67[4];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:27;
            vuint32_t CGCE:1;
            vuint32_t IEHS:1;
            vuint32_t IEHF:1;
            vuint32_t IEBE:1;
            vuint32_t IECC:1;
        } B;
    } MTL_EST_INTR_ENABLE;

    vuint8_t ADR_reserved68[12];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_3:8;
            vuint32_t ESTEIEC:1;
            vuint32_t ESTEIAEE:1;
            vuint32_t ESTEIEE:1;
            vuint32_t unused_2:5;
            vuint32_t ADDR:8;
            vuint32_t unused_1:2;
            vuint32_t DBGB:1;
            vuint32_t DBGM:1;
            vuint32_t unused_0:1;
            vuint32_t GCRR:1;
            vuint32_t R1W0:1;
            vuint32_t SRWO:1;
        } B;
    } MTL_EST_GCL_CONTROL;

    union {
        vuint32_t R;
        struct {
            vuint32_t GCD:32;
        } B;
    } MTL_EST_GCL_DATA;

    vuint8_t ADR_reserved69[8];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_2:3;
            vuint32_t HRS:1;
            vuint32_t unused_1:16;
            vuint32_t PEC:4;
            vuint32_t unused_0:6;
            vuint32_t AFSZ:2;
        } B;
    } MTL_FPE_CTRL_STS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RADV:16;
            vuint32_t HADV:16;
        } B;
    } MTL_FPE_ADVANCE;

    vuint8_t ADR_reserved70[8];

    union {
        vuint32_t R;
        struct {
            vuint32_t RXPI:1;
            vuint32_t ELIRS:1;
            vuint32_t unused_2:6;
            vuint32_t NPE:8;
            vuint32_t unused_1:4;
            vuint32_t OKI_DME:1;
            vuint32_t unused_0:3;
            vuint32_t NVE:8;
        } B;
    } MTL_RXP_CONTROL_STATUS;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:12;
            vuint32_t PDRFIE:1;
            vuint32_t FOOVIE:1;
            vuint32_t NPEOVIE:1;
            vuint32_t NVEOVIE:1;
            vuint32_t unused_0:12;
            vuint32_t PDRFIS:1;
            vuint32_t FOOVIS:1;
            vuint32_t NPEOVIS:1;
            vuint32_t NVEOVIS:1;
        } B;
    } MTL_RXP_INTERRUPT_CONTROL_STATUS;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXPDCOVF:1;
            vuint32_t RXPDC:31;
        } B;
    } MTL_RXP_DROP_CNT;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXPECOVF:1;
            vuint32_t RXPEC:31;
        } B;
    } MTL_RXP_ERROR_CNT;

    union {
        vuint32_t R;
        struct {
            vuint32_t STARTRBUSY:1;
            vuint32_t unused_2:8;
            vuint32_t RXPEIEC:1;
            vuint32_t RXPEIAEE:1;
            vuint32_t RXPEIEE:1;
            vuint32_t unused_1:3;
            vuint32_t WRRDN:1;
            vuint32_t unused_0:6;
            vuint32_t ADDR:10;
        } B;
    } MTL_RXP_INDIRECT_ACC_CONTROL_STATUS;

    union {
        vuint32_t R;
        struct {
            vuint32_t DATA:32;
        } B;
    } MTL_RXP_INDIRECT_ACC_DATA;

    union {
        vuint32_t R;
        struct {
            vuint32_t RXPBCOF:1;
            vuint32_t RXPC:31;
        } B;
    } MTL_RXP_BYPASS_CNT;

    vuint8_t ADR_reserved71[4];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:23;
            vuint32_t MEEAO:1;
            vuint32_t unused_0:2;
            vuint32_t DSCEE:1;
            vuint32_t TSOEE:1;
            vuint32_t MRXPEE:1;
            vuint32_t MESTEE:1;
            vuint32_t MRXEE:1;
            vuint32_t MTXEE:1;
        } B;
    } MTL_ECC_CONTROL;

    union {
        vuint32_t R;
        struct {
            vuint32_t MCSIS:1;
            vuint32_t unused_0:29;
            vuint32_t MEUIS:1;
            vuint32_t MECIS:1;
        } B;
    } MTL_SAFETY_INTERRUPT_STATUS;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_3:19;
            vuint32_t RPCEIE:1;
            vuint32_t unused_2:3;
            vuint32_t ECEIE:1;
            vuint32_t unused_1:3;
            vuint32_t RXCEIE:1;
            vuint32_t unused_0:3;
            vuint32_t TXCEIE:1;
        } B;
    } MTL_ECC_INTERRUPT_ENABLE;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_3:17;
            vuint32_t RPUES:1;
            vuint32_t RPAMS:1;
            vuint32_t RPCES:1;
            vuint32_t unused_2:1;
            vuint32_t EUES:1;
            vuint32_t EAMS:1;
            vuint32_t ECES:1;
            vuint32_t unused_1:1;
            vuint32_t RXUES:1;
            vuint32_t RXAMS:1;
            vuint32_t RXCES:1;
            vuint32_t unused_0:1;
            vuint32_t TXUES:1;
            vuint32_t TXAMS:1;
            vuint32_t TXCES:1;
        } B;
    } MTL_ECC_INTERRUPT_STATUS;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:26;
            vuint32_t CUES:1;
            vuint32_t CCES:1;
            vuint32_t EMS:3;
            vuint32_t EESRE:1;
        } B;
    } MTL_ECC_ERR_STS_RCTL;

    union {
        vuint32_t R;
        struct {
            vuint32_t EUEAS:16;
            vuint32_t ECEAS:16;
        } B;
    } MTL_ECC_ERR_ADDR_STATUS;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:12;
            vuint32_t EUEAS:4;
            vuint32_t unused_0:8;
            vuint32_t ECECS:8;
        } B;
    } MTL_ECC_ERR_CNTR_STATUS;

    vuint8_t ADR_reserved72[4];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:15;
            vuint32_t IPEDC:1;
            vuint32_t IPEMRWC:1;
            vuint32_t IPEMTFC:1;
            vuint32_t IPEMTBU:1;
            vuint32_t IPEASR:1;
            vuint32_t IPEMSW:1;
            vuint32_t IPEASW:1;
            vuint32_t IPERID:1;
            vuint32_t IPEMTS:1;
            vuint32_t IPEMTF:1;
            vuint32_t IPETRD:1;
            vuint32_t IPETH:1;
            vuint32_t IPETID:1;
            vuint32_t unused_0:1;
            vuint32_t EPSI:1;
            vuint32_t OPE:1;
            vuint32_t EDPP:1;
        } B;
    } MTL_DPP_CONTROL;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:15;
            vuint32_t EIM:1;
            vuint32_t unused_0:8;
            vuint32_t BLEI:8;
        } B;
    } MTL_DPP_ECC_EIC;

    vuint8_t ADR_reserved73[24];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:10;
            vuint32_t TQS:6;
            vuint32_t unused_0:9;
            vuint32_t TTC:3;
            vuint32_t TXQEN:2;
            vuint32_t TSF:1;
            vuint32_t FTQ:1;
        } B;
    } MTL_TXQ0_OPERATION_MODE;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:20;
            vuint32_t UFCNTOVF:1;
            vuint32_t UFFRMCNT:11;
        } B;
    } MTL_TXQ0_UNDERFLOW;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_2:9;
            vuint32_t STXSTSF:3;
            vuint32_t unused_1:1;
            vuint32_t PTXQ:3;
            vuint32_t unused_0:10;
            vuint32_t TXSTSFSTS:1;
            vuint32_t TXQSTS:1;
            vuint32_t TWCSTS:1;
            vuint32_t TRCSTS:2;
            vuint32_t TXQPAUSED:1;
        } B;
    } MTL_TXQ0_DEBUG;

    vuint8_t ADR_reserved74[8];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:8;
            vuint32_t ABS:24;
        } B;
    } MTL_TXQ0_ETS_STATUS;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:11;
            vuint32_t ISCQW:21;
        } B;
    } MTL_TXQ0_QUANTUM_WEIGHT;

    vuint8_t ADR_reserved75[16];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_3:7;
            vuint32_t RXOIE:1;
            vuint32_t unused_2:7;
            vuint32_t RXOVFIS:1;
            vuint32_t unused_1:6;
            vuint32_t ABPSIE:1;
            vuint32_t TXUIE:1;
            vuint32_t unused_0:6;
            vuint32_t ABPSIS:1;
            vuint32_t TXUNFIS:1;
        } B;
    } MTL_Q0_INTERRUPT_CONTROL_STATUS;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_3:6;
            vuint32_t RQS:6;
            vuint32_t unused_2:1;
            vuint32_t RFD:5;
            vuint32_t unused_1:1;
            vuint32_t RFA:5;
            vuint32_t EHFC:1;
            vuint32_t DIS_TCP_EF:1;
            vuint32_t RSF:1;
            vuint32_t FEP:1;
            vuint32_t FUP:1;
            vuint32_t unused_0:1;
            vuint32_t RTC:2;
        } B;
    } MTL_RXQ0_OPERATION_MODE;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:4;
            vuint32_t MISCNTOVF:1;
            vuint32_t MISPKTCNT:11;
            vuint32_t unused_0:4;
            vuint32_t OVFCNTOVF:1;
            vuint32_t OVFPKTCNT:11;
        } B;
    } MTL_RXQ0_MISSED_PACKET_OVERFLOW_CNT;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_2:2;
            vuint32_t PRXQ:14;
            vuint32_t unused_1:10;
            vuint32_t RXQSTS:2;
            vuint32_t unused_0:1;
            vuint32_t RRCSTS:2;
            vuint32_t RWCSTS:1;
        } B;
    } MTL_RXQ0_DEBUG;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:28;
            vuint32_t RXQ_FRM_ARBIT:1;
            vuint32_t RXQ_WEGT:3;
        } B;
    } MTL_RXQ0_CONTROL;

    struct {
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:10;
                vuint32_t TQS:6;
                vuint32_t unused_0:9;
                vuint32_t TTC:3;
                vuint32_t TXQEN:2;
                vuint32_t TSF:1;
                vuint32_t FTQ:1;
            } B;
        } MTL_TXQ_OPERATION_MODE;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_0:20;
                vuint32_t UFCNTOVF:1;
                vuint32_t UFFRMCNT:11;
            } B;
        } MTL_TXQ_UNDERFLOW;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_2:9;
                vuint32_t STXSTSF:3;
                vuint32_t unused_1:1;
                vuint32_t PTXQ:3;
                vuint32_t unused_0:10;
                vuint32_t TXSTSFSTS:1;
                vuint32_t TXQSTS:1;
                vuint32_t TWCSTS:1;
                vuint32_t TRCSTS:2;
                vuint32_t TXQPAUSED:1;
            } B;
        } MTL_TXQ_DEBUG;

        vuint8_t ADR_reserved76[4];

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:25;
                vuint32_t SLC:3;
                vuint32_t CC:1;
                vuint32_t AVALG:1;
                vuint32_t unused_0:2;
            } B;
        } MTL_TXQ_ETS_CONTROL;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_0:8;
                vuint32_t ABS:24;
            } B;
        } MTL_TXQ_ETS_STATUS;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_0:11;
                vuint32_t ISCQW:21;
            } B;
        } MTL_TXQ_QUANTUM_WEIGHT;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_0:18;
                vuint32_t SSC:14;
            } B;
        } MTL_TXQ_SENDSLOPECREDIT;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_0:3;
                vuint32_t HC:29;
            } B;
        } MTL_TXQ_HICREDIT;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_0:3;
                vuint32_t LC:29;
            } B;
        } MTL_TXQ_LOCREDIT;

        vuint8_t ADR_reserved77[4];

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_3:7;
                vuint32_t RXOIE:1;
                vuint32_t unused_2:7;
                vuint32_t RXOVFIS:1;
                vuint32_t unused_1:6;
                vuint32_t ABPSIE:1;
                vuint32_t TXUIE:1;
                vuint32_t unused_0:6;
                vuint32_t ABPSIS:1;
                vuint32_t TXUNFIS:1;
            } B;
        } MTL_Q_INTERRUPT_CONTROL_STATUS;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_3:6;
                vuint32_t RQS:6;
                vuint32_t unused_2:1;
                vuint32_t RFD:5;
                vuint32_t unused_1:1;
                vuint32_t RFA:5;
                vuint32_t EHFC:1;
                vuint32_t DIS_TCP_EF:1;
                vuint32_t RSF:1;
                vuint32_t FEP:1;
                vuint32_t FUP:1;
                vuint32_t unused_0:1;
                vuint32_t RTC:2;
            } B;
        } MTL_RXQ_OPERATION_MODE;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:4;
                vuint32_t MISCNTOVF:1;
                vuint32_t MISPKTCNT:11;
                vuint32_t unused_0:4;
                vuint32_t OVFCNTOVF:1;
                vuint32_t OVFPKTCNT:11;
            } B;
        } MTL_RXQ_MISSED_PACKET_OVERFLOW_CNT;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_2:2;
                vuint32_t PRXQ:14;
                vuint32_t unused_1:10;
                vuint32_t RXQSTS:2;
                vuint32_t unused_0:1;
                vuint32_t RRCSTS:2;
                vuint32_t RWCSTS:1;
            } B;
        } MTL_RXQ_DEBUG;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_0:28;
                vuint32_t RXQ_FRM_ARBIT:1;
                vuint32_t RXQ_WEGT:3;
            } B;
        } MTL_RXQ_CONTROL;

    } MTL_Q[3];

    vuint8_t ADR_reserved78[512];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_3:8;
            vuint32_t RNDF:2;
            vuint32_t TNDF:2;
            vuint32_t DCHE:1;
            vuint32_t unused_2:1;
            vuint32_t INTM:2;
            vuint32_t unused_1:1;
            vuint32_t PR:3;
            vuint32_t TXPR:1;
            vuint32_t SCSW:1;
            vuint32_t ARBC:1;
            vuint32_t DSPW:1;
            vuint32_t unused_0:3;
            vuint32_t TAA:3;
            vuint32_t DA:1;
            vuint32_t SWR:1;
        } B;
    } DMA_MODE;

    union {
        vuint32_t R;
        struct {
            vuint32_t EN_LPI:1;
            vuint32_t LPI_XIT_PKT:1;
            vuint32_t unused_2:3;
            vuint32_t WR_OSR_LMT:3;
            vuint32_t unused_1:5;
            vuint32_t RD_OSR_LMT:3;
            vuint32_t RB:1;
            vuint32_t MB:1;
            vuint32_t ONEKBBE:1;
            vuint32_t AAL:1;
            vuint32_t EAME:1;
            vuint32_t AALE:1;
            vuint32_t unused_0:2;
            vuint32_t BLEN256:1;
            vuint32_t BLEN128:1;
            vuint32_t BLEN64:1;
            vuint32_t BLEN32:1;
            vuint32_t BLEN16:1;
            vuint32_t BLEN8:1;
            vuint32_t BLEN4:1;
            vuint32_t FB:1;
        } B;
    } DMA_SYSBUS_MODE;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:14;
            vuint32_t MACIS:1;
            vuint32_t MTLIS:1;
            vuint32_t unused_0:8;
            vuint32_t DC7IS:1;
            vuint32_t DC6IS:1;
            vuint32_t DC5IS:1;
            vuint32_t DC4IS:1;
            vuint32_t DC3IS:1;
            vuint32_t DC2IS:1;
            vuint32_t DC1IS:1;
            vuint32_t DC0IS:1;
        } B;
    } DMA_INTERRUPT_STATUS;

    union {
        vuint32_t R;
        struct {
            vuint32_t TPS2:4;
            vuint32_t RPS2:4;
            vuint32_t TPS1:4;
            vuint32_t RPS1:4;
            vuint32_t TPS0:4;
            vuint32_t RPS0:4;
            vuint32_t unused_0:6;
            vuint32_t AXRHSTS:1;
            vuint32_t AXWHSTS:1;
        } B;
    } DMA_DEBUG_STATUS0;

    union {
        vuint32_t R;
        struct {
            vuint32_t TPS6:4;
            vuint32_t RPS6:4;
            vuint32_t TPS5:4;
            vuint32_t RPS5:4;
            vuint32_t TPS4:4;
            vuint32_t RPS4:4;
            vuint32_t TPS3:4;
            vuint32_t RPS3:4;
        } B;
    } DMA_DEBUG_STATUS1;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:24;
            vuint32_t TPS3:4;
            vuint32_t RPS3:4;
        } B;
    } DMA_DEBUG_STATUS2;

    vuint8_t ADR_reserved79[8];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_3:10;
            vuint32_t THD:2;
            vuint32_t THC:4;
            vuint32_t unused_1:2;
            vuint32_t TED:2;
            vuint32_t TEC:4;
            vuint32_t unused_0:2;
            vuint32_t TDRD:2;
            vuint32_t TDRC:4;
        } B;
    } AXI4_TX_AR_ACE_CONTROL;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_3:2;
            vuint32_t RDD:2;
            vuint32_t RDC:4;
            vuint32_t unused_2:2;
            vuint32_t RHD:2;
            vuint32_t RHC:4;
            vuint32_t unused_1:2;
            vuint32_t RPD:2;
            vuint32_t RPC:4;
            vuint32_t unused_0:2;
            vuint32_t RDWD:2;
            vuint32_t RDWC:4;
        } B;
    } AXI4_RX_AW_ACE_CONTROL;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_3:9;
            vuint32_t WRP:3;
            vuint32_t unused_2:1;
            vuint32_t RDP:3;
            vuint32_t unused_1:2;
            vuint32_t RDRD:2;
            vuint32_t RDRC:4;
            vuint32_t unused_0:2;
            vuint32_t TDWD:2;
            vuint32_t TDWC:4;
        } B;
    } AXI4_TXRX_AWAR_ACE_CONTROL;

    vuint8_t ADR_reserved80[20];

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:28;
            vuint32_t LPIEI:4;
        } B;
    } AXI_LPI_ENTRY_INTERVAL;

    vuint8_t ADR_reserved81[12];

    union {
        vuint32_t R;
        struct {
            vuint32_t FTOS:24;
            vuint32_t unused_1:1;
            vuint32_t FGOS:3;
            vuint32_t unused_0:3;
            vuint32_t FTOV:1;
        } B;
    } DMA_TBS_CTRL0;

    union {
        vuint32_t R;
        struct {
            vuint32_t FTOS:24;
            vuint32_t unused_1:1;
            vuint32_t FGOS:3;
            vuint32_t unused_0:3;
            vuint32_t FTOV:1;
        } B;
    } DMA_TBS_CTRL1;

    union {
        vuint32_t R;
        struct {
            vuint32_t FTOS:24;
            vuint32_t unused_1:1;
            vuint32_t FGOS:3;
            vuint32_t unused_0:3;
            vuint32_t FTOV:1;
        } B;
    } DMA_TBS_CTRL2;

    union {
        vuint32_t R;
        struct {
            vuint32_t FTOS:24;
            vuint32_t unused_1:1;
            vuint32_t FGOS:3;
            vuint32_t unused_0:3;
            vuint32_t FTOV:1;
        } B;
    } DMA_TBS_CTRL3;

    vuint8_t ADR_reserved82[32];

    union {
        vuint32_t R;
        struct {
            vuint32_t MCSIS:1;
            vuint32_t unused_1:1;
            vuint32_t MSUIS:1;
            vuint32_t MSCIS:1;
            vuint32_t unused_0:26;
            vuint32_t DEUIS:1;
            vuint32_t DECIS:1;
        } B;
    } DMA_SAFETY_INTERRUPT_STATUS;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_0:30;
            vuint32_t DCEIE:1;
            vuint32_t TCEIE:1;
        } B;
    } DMA_ECC_INTERRUPT_ENABLE;

    union {
        vuint32_t R;
        struct {
            vuint32_t unused_1:25;
            vuint32_t DUES:1;
            vuint32_t DAMS:1;
            vuint32_t DCES:1;
            vuint32_t unused_0:1;
            vuint32_t TUES:1;
            vuint32_t TAMS:1;
            vuint32_t TCES:1;
        } B;
    } DMA_ECC_INTERRUPT_STATUS;

    vuint8_t ADR_reserved83[116];

    struct {
        union {
            vuint32_t R;
            struct {
                vuint32_t unused_3:7;
                vuint32_t SPH:1;
                vuint32_t unused_2:3;
                vuint32_t DSL:3;
                vuint32_t unused_1:1;
                vuint32_t PBLX8:1;
                vuint32_t unused_0:2;
                vuint32_t MSS:14;
            } B;
        } DMA_CH_CONTROL;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_2:1;
                vuint32_t TFSEL:2;
                vuint32_t EDSE:1;
                vuint32_t TQOS:4;
                vuint32_t unused_1:1;
                vuint32_t ETIC:1;
                vuint32_t TXPBL:6;
                vuint32_t IPBL:1;
                vuint32_t TSE_MODE:2;
                vuint32_t TSE:1;
                vuint32_t unused_0:7;
                vuint32_t OSF:1;
                vuint32_t TCW:3;
                vuint32_t ST:1;
            } B;
        } DMA_CH_TX_CONTROL;

        union {
            vuint32_t R;
            struct {
                vuint32_t RPF:1;
                vuint32_t unused_2:3;
                vuint32_t RQOS:4;
                vuint32_t unused_1:1;
                vuint32_t ERIC:1;
                vuint32_t RXPBL:6;
                vuint32_t unused_0:1;
                vuint32_t RBSZ_13_Y:11;
                vuint32_t RBSZ_X_0:3;
                vuint32_t SR:1;
            } B;
        } DMA_CH_RX_CONTROL;

        vuint8_t ADR_reserved84[4];

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_0:16;
                vuint32_t TDESHA:16;
            } B;
        } DMA_CH_TXDESC_LIST_HADDRESS;

        union {
            vuint32_t R;
            struct {
                vuint32_t TDESLA:29;
                vuint32_t unused_0:3;
            } B;
        } DMA_CH_TXDESC_LIST_ADDRESS;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_0:16;
                vuint32_t RDESHA:16;
            } B;
        } DMA_CH_RXDESC_LIST_HADDRESS;

        union {
            vuint32_t R;
            struct {
                vuint32_t RDESLA:29;
                vuint32_t unused_0:3;
            } B;
        } DMA_CH_RXDESC_LIST_ADDRESS;

        union {
            vuint32_t R;
            struct {
                vuint32_t TDTP:29;
                vuint32_t unused_0:3;
            } B;
        } DMA_CH_TXDESC_TAIL_POINTER;

        vuint8_t ADR_reserved85[4];

        union {
            vuint32_t R;
            struct {
                vuint32_t RDTP:29;
                vuint32_t unused_0:3;
            } B;
        } DMA_CH_RXDESC_TAIL_POINTER;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_0:22;
                vuint32_t TDRL:10;
            } B;
        } DMA_CH_TXDESC_RING_LENGTH;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:8;
                vuint32_t ARBS:7;
                vuint32_t unused_0:7;
                vuint32_t RDRL:10;
            } B;
        } DMA_CH_RX_CONTROL2;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:16;
                vuint32_t NIE:1;
                vuint32_t AIE:1;
                vuint32_t CDEE:1;
                vuint32_t FBEE:1;
                vuint32_t ERIE:1;
                vuint32_t ETIE:1;
                vuint32_t RWTE:1;
                vuint32_t RSE:1;
                vuint32_t RBUE:1;
                vuint32_t RIE:1;
                vuint32_t unused_0:3;
                vuint32_t TBUE:1;
                vuint32_t TXSE:1;
                vuint32_t TIE:1;
            } B;
        } DMA_CH_INTERRUPT_ENABLE;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:14;
                vuint32_t RWTU:2;
                vuint32_t unused_0:8;
                vuint32_t RWT:8;
            } B;
        } DMA_CH_RX_INTERRUPT_WATCHDOG_TIMER;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:12;
                vuint32_t RSN:4;
                vuint32_t SIV:12;
                vuint32_t unused_0:2;
                vuint32_t ASC:1;
                vuint32_t ESC:1;
            } B;
        } DMA_CH_SLOT_FUNCTION_CONTROL_STATUS;

        vuint8_t ADR_reserved86[4];

        union {
            vuint32_t R;
            struct {
                vuint32_t CURTDESAPTR:32;
            } B;
        } DMA_CH_CURRENT_APP_TXDESC;

        vuint8_t ADR_reserved87[4];

        union {
            vuint32_t R;
            struct {
                vuint32_t CURRDESAPTR:32;
            } B;
        } DMA_CH_CURRENT_APP_RXDESC;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_0:16;
                vuint32_t CURTBUFAPTRH:16;
            } B;
        } DMA_CH_CURRENT_APP_TXBUFFER_H;

        union {
            vuint32_t R;
            struct {
                vuint32_t CURTBUFAPTR:32;
            } B;
        } DMA_CH_CURRENT_APP_TXBUFFER;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_0:16;
                vuint32_t CURRBUFAPTRH:16;
            } B;
        } DMA_CH_CURRENT_APP_RXBUFFER_H;

        union {
            vuint32_t R;
            struct {
                vuint32_t CURRBUFAPTR:32;
            } B;
        } DMA_CH_CURRENT_APP_RXBUFFER;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:10;
                vuint32_t REB:3;
                vuint32_t TEB:3;
                vuint32_t NIS:1;
                vuint32_t AIS:1;
                vuint32_t CDE:1;
                vuint32_t FBE:1;
                vuint32_t ERI:1;
                vuint32_t ETI:1;
                vuint32_t RWT:1;
                vuint32_t RPS:1;
                vuint32_t RBU:1;
                vuint32_t RI:1;
                vuint32_t unused_0:3;
                vuint32_t TBU:1;
                vuint32_t TPS:1;
                vuint32_t TI:1;
            } B;
        } DMA_CH_STATUS;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_1:16;
                vuint32_t MFCO:1;
                vuint32_t unused_0:4;
                vuint32_t MFC:11;
            } B;
        } DMA_CH_MISS_FRAME_CNT;

        union {
            vuint32_t R;
            struct {
                vuint32_t RXPACOF:1;
                vuint32_t RXPAC:31;
            } B;
        } DMA_CH_RXP_ACCEPT_CNT;

        union {
            vuint32_t R;
            struct {
                vuint32_t unused_0:20;
                vuint32_t ECNT:12;
            } B;
        } DMA_CH_RX_ERI_CNT;

        vuint8_t ADR_reserved88[16];
    } DMA_CH[4];
};
#endif
